// Category 6: Chai & Lo-fi (lofi) - 200 Chill, Aesthetic, Chai Lo-fi & Indie Melodies
module.exports = [
  { title: "Baarishein", artist: "Anuv Jain", album: "Baarishein", yt: "8lZTEsmk8hw" },
  { title: "Ocean", artist: "Anuv Jain", album: "Ocean", yt: "cNVtYMhBG4I" },
  { title: "Riha", artist: "Anuv Jain", album: "Riha", yt: "posL_V_j4bA" },
  { title: "Mishri", artist: "Anuv Jain", album: "Mishri", yt: "1xYZeDReUz4" },
  { title: "Alag Aasman", artist: "Anuv Jain", album: "Alag Aasman", yt: "NZ1EBaqDL0M" },
  { title: "Gul", artist: "Anuv Jain", album: "Gul", yt: "FewWUHxY79w" },
  { title: "Mazaak", artist: "Anuv Jain", album: "Mazaak", yt: "YDAWpY747TY" },
  { title: "Husn", artist: "Anuv Jain", album: "Husn", yt: "M5n7994yM0c" },
  { title: "cold/mess", artist: "Prateek Kuhad", album: "cold/mess", yt: "cl0a3i2wFcc" },
  { title: "Kasoor", artist: "Prateek Kuhad", album: "Kasoor", yt: "7L_Qv9_zXw0" },
  { title: "Kho Gaye Hum Kahan", artist: "Jasleen Royal, Prateek Kuhad", album: "Baar Baar Dekho", yt: "w-v_0Z9k1_E" },
  { title: "Din Shagna Da", artist: "Jasleen Royal", album: "Phillauri", yt: "v91pX_8v9yE" },
  { title: "Nit Nit", artist: "Jasleen Royal", album: "Nit Nit", yt: "284Ov7ysmfA" },
  { title: "Sang Rahiyo", artist: "Jasleen Royal, Ujjwal Kashyap", album: "Sang Rahiyo", yt: "6FURuLYrR_Q" },
  { title: "Liggi", artist: "Ritviz", album: "Liggi", yt: "w_HaezV04qI" },
  { title: "Jeet", artist: "Ritviz", album: "Jeet", yt: "d4OGrMv_hN0" },
  { title: "Pran", artist: "Ritviz", album: "Pran", yt: "y0p7o1eW9_A" },
  { title: "Roshni", artist: "Ritviz", album: "Roshni", yt: "uN7Wp_q0L3w" },
  { title: "Thandi Hawa", artist: "Ritviz", album: "Thandi Hawa", yt: "fdubeMFwuGs" },
  { title: "Choo Lo", artist: "The Local Train", album: "Aalas Ka Pedh", yt: "qnQCd_nZn_g" },
  { title: "Aaoge Tum Kabhi", artist: "The Local Train", album: "Aalas Ka Pedh", yt: "bjfKyIAlsZs" },
  { title: "Dil Mere", artist: "The Local Train", album: "Vaaqif", yt: "pCYojfACnzQ" },
  { title: "Aftab", artist: "The Local Train", album: "Vaaqif", yt: "BddP6PYo2gs" },
  { title: "Vaaqif", artist: "The Local Train", album: "Vaaqif", yt: "QXJyMpxd210" },
  { title: "Mizaaj", artist: "The Local Train", album: "Vaaqif", yt: "taRBVfDRukY" },
  { title: "Waqt Ki Baatein", artist: "Dream Note", album: "Waqt Ki Baatein", yt: "y9kQ5L_X8rE" },
  { title: "Faasle", artist: "Aditya Rikhari", album: "Faasle", yt: "k6vN0qP91C0" },
  { title: "Samjho Na", artist: "Aditya Rikhari", album: "Samjho Na", yt: "8v-0h5xY6gE" },
  { title: "Kya Karoon", artist: "Zaeden", album: "Kya Karoon", yt: "p8L3n9X0vY0" },
  { title: "Main Dhoondne Ko Zamaane Mein", artist: "Arijit Singh, Gaurav Dagaonkar", album: "Heartless", yt: "Ov0YGGSY6gY" },
  { title: "Ishq Bulaava", artist: "Sanam Puri, Shipra Goyal, Vishal-Shekhar", album: "Hasee Toh Phasee", yt: "OOWvmeTTp7Y" },
  { title: "Zehnaseeb", artist: "Chinmayi Sripada, Shekhar Ravjiani", album: "Hasee Toh Phasee", yt: "cYOB941gyXI" },
  { title: "Mann Mera", artist: "Gajendra Verma", album: "Table No. 21", yt: "cs1e0fRyI18" },
  { title: "Saibo", artist: "Shreya Ghoshal, Sachin-Jigar", album: "Shor in the City", yt: "CWHSNIpl7dg" },
  { title: "Aabaad Barbaad", artist: "Arijit Singh, Pritam", album: "Ludo", yt: "2Vv-BfVoq4g" },
  { title: "Hardum Humdum", artist: "Arijit Singh, Pritam", album: "Ludo", yt: "Pa1UPI5STLk" },
  { title: "Meri Jaan", artist: "Neeti Mohan, Sanjay Leela Bhansali", album: "Gangubai Kathiawadi", yt: "7shxWODIwqs" },
  { title: "Jab Saaiyaan", artist: "Shreya Ghoshal, Sanjay Leela Bhansali", album: "Gangubai Kathiawadi", yt: "zVUKtXI7xTM" },
  { title: "Shauq", artist: "Shahid Mallya, Sireesha Bhagavatula, Amit Trivedi", album: "Qala", yt: "g6C-GUy6a3s" },
  { title: "Ghodey Pe Sawaar", artist: "Sireesha Bhagavatula, Amit Trivedi", album: "Qala", yt: "ElZfdU54Cp8" },
  { title: "Phero Na Najariya", artist: "Sireesha Bhagavatula, Amit Trivedi", album: "Qala", yt: "KUpwupYj_tY" },
  { title: "Nirbhau Nirvair", artist: "Amit Trivedi, Swanand Kirkire", album: "Qala", yt: "iAOA8TLgqG8" },
  { title: "Iktara", artist: "Kavita Seth, Amitabh Bhattacharya, Amit Trivedi", album: "Wake Up Sid", yt: "PVxc5f4GJU8" },
  { title: "Wake Up Sid Club Mix", artist: "Shankar Mahadevan, Loy Mendonsa", album: "Wake Up Sid", yt: "j6muwUGPCl8" },
  { title: "Life Is Crazy", artist: "Uday Benegal, Shankar-Ehsaan-Loy", album: "Wake Up Sid", yt: "wF_B_a30AZc" },
  { title: "Sham", artist: "Amit Trivedi, Nikhil D'Souza, Neuman Pinto", album: "Aisha", yt: "SAcpESN_Fk4" },
  { title: "Suno Aisha", artist: "Amit Trivedi, Ash King, Nakash Aziz", album: "Aisha", yt: "rTuxUAuJRyY" },
  { title: "Lehrein", artist: "Anusha Mani, Neuman Pinto, Amit Trivedi", album: "Aisha", yt: "P8PWN1OmZOA" },
  { title: "Gulaabo", artist: "Vishal Dadlani, Anusha Mani, Amit Trivedi", album: "Shaandaar", yt: "g5dnox-gqE8" },
  { title: "Nazm Nazm", artist: "Arko", album: "Bareilly Ki Barfi", yt: "vskH_fBq2rU" }
];
