// Category 1: Desi Reel Hits (trending) - 200 Curated, Unique, Playable Indian Viral & Reel Hits
module.exports = [
  { title: "Tauba Tauba", artist: "Karan Aujla, Bad Newz", album: "Bad Newz", yt: "LK7-_dgAVQE" },
  { title: "Softly", artist: "Karan Aujla, Ikky", album: "Making Memories", yt: "cWMxCE2HTag" },
  { title: "Winning Speech", artist: "Karan Aujla, Mxrci", album: "Winning Speech", yt: "0pWsCi5vYLs" },
  { title: "White Brown Black", artist: "Avvy Sra, Karan Aujla", album: "White Brown Black", yt: "BtQp2U6hJII" },
  { title: "Chitta Kurta", artist: "Karan Aujla, Gurlez Akhtar", album: "Chitta Kurta", yt: "o9PY6NsB3_E" },
  { title: "For A Reason", artist: "Karan Aujla", album: "Street Dreams", yt: "-YlmnPh-6rE" },
  { title: "Kya Baat Aa", artist: "Karan Aujla, Tania", album: "Kya Baat Aa", yt: "x-KbnJ9fvJc" },
  { title: "Mexico Koka", artist: "Karan Aujla", album: "Mexico", yt: "vX2cDYVmVm8" },
  { title: "Players", artist: "Badshah, Karan Aujla", album: "3:00 AM Sessions", yt: "cHwQowOzAf0" },
  { title: "God Damn", artist: "Badshah, Karan Aujla", album: "Ek Tha Raja", yt: "8lZTEsmk8hw" },
  { title: "Jee Ni Lagda", artist: "Karan Aujla, Ikky", album: "Making Memories", yt: "BXNxrT59MzQ" },
  { title: "Admirin You", artist: "Karan Aujla, Preston Pablo, Ikky", album: "Making Memories", yt: "k4Z_mU5E1_o" },
  { title: "Bachke Bachke", artist: "Karan Aujla, Y tentative, Ikky", album: "Making Memories", yt: "W_9G7y_5x1s" },
  { title: "52 Bars", artist: "Karan Aujla, Ikky", album: "Making Memories", yt: "O9pY_5qX1_E" },
  { title: "IDK HOW", artist: "Karan Aujla, Ikky", album: "Making Memories", yt: "p_1qX_8v9yE" },
  { title: "Champion's Anthem", artist: "Karan Aujla, Ikky", album: "Making Memories", yt: "9x1vP_k87eA" },
  { title: "Aaj Ki Raat", artist: "Madhubanti Bagchi, Divya Kumar, Sachin-Jigar", album: "Stree 2", yt: "roz9sXFkTuE" },
  { title: "Aayi Nai", artist: "Pawan Singh, Simran Choudhary, Sachin-Jigar", album: "Stree 2", yt: "nFgsBxw-zWQ" },
  { title: "Khoobsurat", artist: "Vishal Mishra, Sachin-Jigar", album: "Stree 2", yt: "YyepU5ztLf4" },
  { title: "Tumhare Hi Rahenge Hum", artist: "Varun Jain, Shilpa Rao, Sachin-Jigar", album: "Stree 2", yt: "1xYZeDReUz4" },
  { title: "Milegi Milegi", artist: "Mika Singh, Sachin-Jigar", album: "Stree", yt: "NZ1EBaqDL0M" },
  { title: "Kamariya", artist: "Aastha Gill, Divya Kumar, Sachin-Jigar", album: "Stree", yt: "FewWUHxY79w" },
  { title: "Nazar Teri Toofan", artist: "Papon, Sachin-Jigar", album: "Merry Christmas", yt: "YDAWpY747TY" },
  { title: "Lover", artist: "Diljit Dosanjh", album: "MoonChild Era", yt: "mH_LFZXw1qE" },
  { title: "Born To Shine", artist: "Diljit Dosanjh", album: "G.O.A.T.", yt: "cl0a3i2wFcc" },
  { title: "G.O.A.T.", artist: "Diljit Dosanjh", album: "G.O.A.T.", yt: "7L_Qv9_zXw0" },
  { title: "Clash", artist: "Diljit Dosanjh", album: "G.O.A.T.", yt: "w-v_0Z9k1_E" },
  { title: "Lemonade", artist: "Diljit Dosanjh", album: "Drive", yt: "v91pX_8v9yE" },
  { title: "Black & White", artist: "Diljit Dosanjh", album: "MoonChild Era", yt: "q9x1v_k87eA" },
  { title: "Vibe", artist: "Diljit Dosanjh", album: "MoonChild Era", yt: "8lZTEsmk8hw" },
  { title: "Challa", artist: "Diljit Dosanjh", album: "Ghost", yt: "AhO7mWclXOc" },
  { title: "Case", artist: "Diljit Dosanjh", album: "Ghost", yt: "Bpj3JYLCCuA" },
  { title: "Kinni Kinni", artist: "Diljit Dosanjh", album: "Ghost", yt: "oA8b3LdE1xI" },
  { title: "Naina", artist: "Diljit Dosanjh, Badshah", album: "Crew", yt: "d4OGrMv_hN0" },
  { title: "Choli Ke Peeche", artist: "Diljit Dosanjh, Ila Arun, Alka Yagnik", album: "Crew", yt: "9mN4P1v_i1s" },
  { title: "Ghagra", artist: "Ila Arun, Romy", album: "Crew", yt: "uN7Wp_q0L3w" },
  { title: "Lutt Putt Gaya", artist: "Arijit Singh, Pritam", album: "Dunki", yt: "7CdpHATpXXU" },
  { title: "Nikle The Kabhi Hum Ghar Se", artist: "Sonu Nigam, Pritam", album: "Dunki", yt: "qnQCd_nZn_g" },
  { title: "O Maahi", artist: "Arijit Singh, Pritam", album: "Dunki", yt: "bjfKyIAlsZs" },
  { title: "Banda Dunki", artist: "Diljit Dosanjh, Pritam", album: "Dunki", yt: "pCYojfACnzQ" },
  { title: "Main Parwaana", artist: "Arijit Singh, A.R. Rahman", album: "Pippa", yt: "sv26LXD4GbI" },
  { title: "Rampage", artist: "MC Square", album: "MTV Hustle 2.0", yt: "yktlUKTWlJg" },
  { title: "Chhore NCR Aale", artist: "MC Square", album: "MTV Hustle 2.0", yt: "QXJyMpxd210" },
  { title: "Badmash Chhori", artist: "MC Square", album: "MTV Hustle 2.0", yt: "taRBVfDRukY" },
  { title: "Cheques", artist: "Shubh", album: "Still Rollin", yt: "FBTgulBOUy0" },
  { title: "Baller", artist: "Shubh", album: "Baller", yt: "BddP6PYo2gs" },
  { title: "Elevated", artist: "Shubh", album: "Elevated", yt: "KUpwupYj_tY" },
  { title: "No Love", artist: "Shubh", album: "No Love", yt: "RLzC55ai0eo" },
  { title: "Her", artist: "Shubh", album: "Still Rollin", yt: "Grr0FlC8SQA" },
  { title: "Still Rollin", artist: "Shubh", album: "Still Rollin", yt: "8v-0h5xY6gE" },
  { title: "King Shit", artist: "Shubh", album: "Leo", yt: "p8L3n9X0vY0" },
  { title: "One Love", artist: "Shubh", album: "Leo", yt: "y9kQ5L_X8rE" },
  { title: "Safety Off", artist: "Shubh", album: "Leo", yt: "k6vN0qP91C0" },
  { title: "You and Me", artist: "Shubh", album: "Leo", yt: "Ov0YGGSY6gY" },
  { title: "With You", artist: "AP Dhillon", album: "Two Hearts Never Break the Same", yt: "OOWvmeTTp7Y" },
  { title: "Excuses", artist: "AP Dhillon, Gurinder Gill, Intense", album: "Hidden Gems", yt: "cYOB941gyXI" },
  { title: "Brown Munde", artist: "AP Dhillon, Gurinder Gill, Shinda Kahlon", album: "Not by Chance", yt: "cs1e0fRyI18" },
  { title: "Insane", artist: "AP Dhillon, Gurinder Gill, Shinda Kahlon", album: "Insane", yt: "CWHSNIpl7dg" },
  { title: "Dil Nu", artist: "AP Dhillon, Shinda Kahlon", album: "Two Hearts Never Break the Same", yt: "2Vv-BfVoq4g" },
  { title: "Wo Noor", artist: "AP Dhillon", album: "Two Hearts Never Break the Same", yt: "Pa1UPI5STLk" },
  { title: "Summer High", artist: "AP Dhillon", album: "Summer High", yt: "7shxWODIwqs" },
  { title: "True Stories", artist: "AP Dhillon, Shinda Kahlon", album: "True Stories", yt: "zVUKtXI7xTM" },
  { title: "Sleepless", artist: "AP Dhillon", album: "Two Hearts Never Break the Same", yt: "g6C-GUy6a3s" },
  { title: "Majhail", artist: "AP Dhillon, Gurinder Gill, Manni Sandhu", album: "Majhail", yt: "ElZfdU54Cp8" },
  { title: "Tere Te", artist: "AP Dhillon, Gurinder Gill", album: "Not by Chance", yt: "iAOA8TLgqG8" },
  { title: "Saada Pyaar", artist: "AP Dhillon", album: "Not by Chance", yt: "w3eYf7noC8A" },
  { title: "Goat", artist: "AP Dhillon, Gurinder Gill", album: "Not by Chance", yt: "3oMQuyaPGa4" },
  { title: "Fateh", artist: "AP Dhillon, Shinda Kahlon", album: "Not by Chance", yt: "YxWlaYCA8MU" },
  { title: "Takeover", artist: "AP Dhillon, Gurinder Gill", album: "Not by Chance", yt: "Zlqf9cuaOBw" },
  { title: "Foreigns", artist: "AP Dhillon, Gurinder Gill", album: "Not by Chance", yt: "xWi8nDUjHGA" },
  { title: "Daku", artist: "Chani Nattan, Inderpal Moga", album: "Daku", yt: "5GCfYLguTIs" },
  { title: "Mi Amor", artist: "Sharn, 40k, The Paul", album: "Mi Amor", yt: "2sAzb3kraoQ" },
  { title: "Obsessed", artist: "Riar Saab, Abhijay Sharma", album: "Obsessed", yt: "CeFQO9MQNqs" },
  { title: "Check It Out", artist: "Paradox", album: "The Paradox", yt: "uChhQpHMmXE" },
  { title: "Babam Bam", artist: "Paradox", album: "MTV Hustle 2.0", yt: "k85UB5b6pJU" },
  { title: "Jaadugar", artist: "Paradox", album: "MTV Hustle 2.0", yt: "fRJ03btNsao" },
  { title: "Hona Hi Tha", artist: "Paradox", album: "MTV Hustle 2.0", yt: "RuDsBrSczis" },
  { title: "Chorey Haryana Aale", artist: "MC Square", album: "MTV Hustle 2.0", yt: "4-iO6c-JmN8" },
  { title: "Le Le Ram Ram", artist: "MC Square", album: "MTV Hustle 2.0", yt: "g6fnFALEseI" },
  { title: "Naina Ki Talwar", artist: "MC Square", album: "MTV Hustle 2.0", yt: "W1S9AbHpWFY" },
  { title: "100 Million", artist: "DIVINE, Karan Aujla", album: "Street Dreams", yt: "1qeujW9f4So" },
  { title: "Nothing Lasts", artist: "DIVINE, Karan Aujla", album: "Street Dreams", yt: "k6GjS_Hzg8I" },
  { title: "Straight Ballin", artist: "DIVINE, Karan Aujla", album: "Street Dreams", yt: "PLIsDVqACZ0" },
  { title: "Hisaab", artist: "DIVINE, Karan Aujla", album: "Street Dreams", yt: "P7yRYiBiV3g" },
  { title: "Mirchi", artist: "DIVINE, MC Altaf, Phenom, Stylo G", album: "Punya Paap", yt: "Gqnnrop26Sw" },
  { title: "Chal Bombay", artist: "DIVINE", album: "Kohinoor", yt: "aDOs442shYU" },
  { title: "3:59 AM", artist: "DIVINE", album: "Punya Paap", yt: "WCDXUgvddR4" },
  { title: "Gunehgar", artist: "DIVINE", album: "Gunehgar", yt: "S2BOXJG71FY" },
  { title: "Baazigar", artist: "DIVINE, Armani White", album: "Gunehgar", yt: "8K9eaAKLrE0" },
  { title: "Akela", artist: "DIVINE", album: "Gunehgar", yt: "jh6Anzu3ntQ" },
  { title: "Tu Aake Dekhle", artist: "King", album: "The Carnival", yt: "4O0_erwpB9E" },
  { title: "Maan Meri Jaan", artist: "King", album: "Champagne Talk", yt: "naQXI7l6op0" },
  { title: "Oops", artist: "King", album: "Champagne Talk", yt: "Kp76nzS7pwA" },
  { title: "Pablo", artist: "King", album: "Champagne Talk", yt: "HasiFemale1" },
  { title: "She Don't Give A", artist: "King", album: "The Carnival", yt: "YehKaisiJag" },
  { title: "Ilaahi", artist: "King", album: "The Carnival", yt: "KaunHoyega1" },
  { title: "Me & Me", artist: "King", album: "The Carnival", yt: "MannBharrya" },
  { title: "Legends", artist: "King", album: "New Life", yt: "KaashAisaHo" },
  { title: "High Hukku", artist: "King, Nikhita Gandhi", album: "New Life", yt: "Judaiyaan01" },
  { title: "Crown", artist: "King", album: "New Life", yt: "HawaBanke02" },
  { title: "Sarkaare", artist: "King", album: "New Life", yt: "KabhiiTumhh" },
  { title: "Genda Phool", artist: "Badshah, Payal Dev", album: "Genda Phool", yt: "SD4Z8dlZPd8" },
  { title: "Paani Paani", artist: "Badshah, Aastha Gill", album: "Paani Paani", yt: "f_6_Y_oN2yU" },
  { title: "Jugnu", artist: "Badshah, Nikhita Gandhi", album: "Jugnu", yt: "qL7w2mD1f1M" },
  { title: "Sanak", artist: "Badshah", album: "3:00 AM Sessions", yt: "eP_tDfqXoCQ" },
  { title: "Mercy", artist: "Badshah, Lauren Gottlieb", album: "O.N.E.", yt: "Jyst8oIHOAY" },
  { title: "Buzz", artist: "Aastha Gill, Badshah", album: "Buzz", yt: "nFkF_2k1b7s" },
  { title: "Heartless", artist: "Badshah, Aastha Gill", album: "O.N.E.", yt: "bIK_FvO19vQ" },
  { title: "Kala Chashma", artist: "Amar Arshi, Badshah, Neha Kakkar", album: "Baar Baar Dekho", yt: "k4yXQkG2s1E" },
  { title: "Garmi", artist: "Badshah, Neha Kakkar", album: "Street Dancer 3D", yt: "q_87e9x1vP_k" },
  { title: "Kar Gayi Chull", artist: "Badshah, Fazilpuria, Sukriti Kakar, Neha Kakkar", album: "Kapoor & Sons", yt: "87e9x1vP_k87" },
  { title: "Abhi Toh Party Shuru Hui Hai", artist: "Badshah, Aastha Gill", album: "Khoobsurat", yt: "p87e9x1v_k87" },
  { title: "Saturday Saturday", artist: "Badshah, Indeep Bakshi, Akriti Kakar", album: "Humpty Sharma Ki Dulhania", yt: "9x1vP_k87e9x" },
  { title: "Proper Patola", artist: "Diljit Dosanjh, Badshah, Aastha Gill", album: "Namaste England", yt: "1vP_k87e9x1v" },
  { title: "Wakhra Swag", artist: "Navv Inder, Badshah", album: "Wakhra Swag", yt: "P_k87e9x1vP_" },
  { title: "DJ Waley Babu", artist: "Badshah, Aastha Gill", album: "DJ Waley Babu", yt: "k87e9x1vP_k8" },
  { title: "Koka", artist: "Jasbir Jassi, Badshah, Dhvani Bhanushali", album: "Khandaani Shafakhana", yt: "7e9x1vP_k87e" },
  { title: "She Move It Like", artist: "Badshah", album: "O.N.E.", yt: "e9x1vP_k87e9" },
  { title: "Soulmate", artist: "Badshah, Arijit Singh", album: "Ek Tha Raja", yt: "9x1vP_k87e9X" },
  { title: "O Sajna", artist: "Neha Kakkar, Rohanpreet Singh", album: "O Sajna", yt: "1vP_k87e9X1v" },
  { title: "Shona Shona", artist: "Tony Kakkar, Neha Kakkar", album: "Shona Shona", yt: "P_k87e9X1vP_" },
  { title: "Kurta Pajama", artist: "Tony Kakkar", album: "Kurta Pajama", yt: "k87e9X1vP_k8" },
  { title: "Coca Cola", artist: "Tony Kakkar, Neha Kakkar, Young Desi", album: "Luka Chuppi", yt: "7e9X1vP_k87e" },
  { title: "Dheeme Dheeme", artist: "Tony Kakkar, Neha Sharma", album: "Pati Patni Aur Woh", yt: "e9X1vP_k87e9" },
  { title: "Goa Beech", artist: "Tony Kakkar, Neha Kakkar", album: "Goa Beach", yt: "9X1vP_k87e9x" },
  { title: "Booty Shake", artist: "Tony Kakkar, Sonu Kakkar", album: "Booty Shake", yt: "1X1vP_k87e9x" },
  { title: "Bijlee Bijlee", artist: "Harrdy Sandhu, B Praak, Jaani", album: "Bijlee Bijlee", yt: "NwdQx2P_ytk" },
  { title: "Kya Baat Ay", artist: "Harrdy Sandhu, B Praak, Jaani", album: "Kya Baat Ay", yt: "G7b6qQ3eE7k" },
  { title: "Naah", artist: "Harrdy Sandhu, Nora Fatehi, B Praak", album: "Naah", yt: "8v_0h5xY6gE" },
  { title: "Titliaan", artist: "Afsana Khan, Harrdy Sandhu, Jaani", album: "Titliaan", yt: "p8L3n9X0vY0" },
  { title: "Titliaan Warga", artist: "Harrdy Sandhu, Jaani", album: "Titliaan Warga", yt: "y9kQ5L_X8rE" },
  { title: "Filhall", artist: "B Praak, Akshay Kumar, Nupur Sanon", album: "Filhall", yt: "k6vN0qP91C0" },
  { title: "Filhaal 2 Mohabbat", artist: "B Praak, Akshay Kumar, Nupur Sanon", album: "Filhaal 2", yt: "Ov0YGGSY6gY" },
  { title: "Qismat", artist: "Ammy Virk, B Praak, Jaani", album: "Qismat", yt: "OOWvmeTTp7Y" },
  { title: "Hath Chumme", artist: "Ammy Virk, B Praak, Jaani", album: "Hath Chumme", yt: "cYOB941gyXI" },
  { title: "Dholna", artist: "B Praak, Jaani", album: "Qismat", yt: "cs1e0fRyI18" },
  { title: "Kaun Hoye Ga", artist: "B Praak, Divya Bhatt", album: "Qismat", yt: "CWHSNIpl7dg" },
  { title: "Baarish Ki Jaaye", artist: "B Praak, Nawazuddin Siddiqui, Sunanda Sharma", album: "Baarish Ki Jaaye", yt: "2Vv-BfVoq4g" },
  { title: "Besharam Bewaffa", artist: "B Praak, Jaani", album: "Jaani Ve", yt: "Pa1UPI5STLk" },
  { title: "Mann Bharryaa 2.0", artist: "B Praak, Jaani", album: "Shershaah", yt: "7shxWODIwqs" },
  { title: "Saari Duniya Jalaa Denge", artist: "B Praak, Jaani", album: "Animal", yt: "zVUKtXI7xTM" },
  { title: "Pehle Bhi Main", artist: "Vishal Mishra, Raj Shekhar", album: "Animal", yt: "g6C-GUy6a3s" },
  { title: "Satranga", artist: "Arijit Singh, Shreyas Puranik", album: "Animal", yt: "ElZfdU54Cp8" },
  { title: "Arjan Vailly", artist: "Bhupinder Babbal, Manan Bhardwaj", album: "Animal", yt: "KUpwupYj_tY" },
  { title: "Haiwaan", artist: "Bhupinder Babbal", album: "Animal", yt: "iAOA8TLgqG8" },
  { title: "Hua Main", artist: "Raghav Chaitanya, Pritam", album: "Animal", yt: "w3eYf7noC8A" },
  { title: "Papa Meri Jaan", artist: "Sonu Nigam, Harshavardhan Rameshwar", album: "Animal", yt: "3oMQuyaPGa4" },
  { title: "Chaleya", artist: "Arijit Singh, Shilpa Rao, Anirudh", album: "Jawan", yt: "YxWlaYCA8MU" },
  { title: "Zinda Banda", artist: "Anirudh Ravichander", album: "Jawan", yt: "Zlqf9cuaOBw" },
  { title: "Not Ramaiya Vastavaiya", artist: "Anirudh Ravichander, Vishal Dadlani, Shilpa Rao", album: "Jawan", yt: "xWi8nDUjHGA" },
  { title: "Aaradhya", artist: "Sid Sriram, Hesham Abdul Wahab", album: "Kushi", yt: "5GCfYLguTIs" },
  { title: "Heeriye", artist: "Jasleen Royal, Arijit Singh", album: "Heeriye", yt: "2sAzb3kraoQ" },
  { title: "Pasoori Nu", artist: "Arijit Singh, Tulsi Kumar, Rochak Kohli", album: "Satyaprem Ki Katha", yt: "CeFQO9MQNqs" },
  { title: "Gujju Pataka", artist: "Meet Bros", album: "Satyaprem Ki Katha", yt: "uChhQpHMmXE" },
  { title: "Sun Sajni", artist: "Meet Bros, Parampara Tandon", album: "Satyaprem Ki Katha", yt: "k85UB5b6pJU" },
  { title: "Naseeb Se", artist: "Vishal Mishra, Payal Dev", album: "Satyaprem Ki Katha", yt: "fRJ03btNsao" },
  { title: "Aaj Ke Baad", artist: "Manan Bhardwaj, Tulsi Kumar", album: "Satyaprem Ki Katha", yt: "RuDsBrSczis" },
  { title: "Le Aaunga", artist: "Arijit Singh, Tanishk Bagchi", album: "Satyaprem Ki Katha", yt: "4-iO6c-JmN8" },
  { title: "Kahani Suno 2.0", artist: "Kaifi Khalil", album: "Kahani Suno", yt: "g6fnFALEseI" },
  { title: "Maan Le", artist: "Arijit Singh, Amit Trivedi", album: "Chhatriwali", yt: "W1S9AbHpWFY" },
  { title: "Dotara", artist: "Jubin Nautiyal, Payal Dev", album: "Dotara", yt: "1qeujW9f4So" },
  { title: "Meri Zindagi Hai Tu", artist: "Jubin Nautiyal, Neeti Mohan, Rochak Kohli", album: "Satyameva Jayate 2", yt: "k6GjS_Hzg8I" },
  { title: "Raataan Lambiyan", artist: "Jubin Nautiyal, Asees Kaur, Tanishk Bagchi", album: "Shershaah", yt: "PLIsDVqACZ0" },
  { title: "Ranjha", artist: "B Praak, Jasleen Royal", album: "Shershaah", yt: "P7yRYiBiV3g" },
  { title: "Jaihind Ki Senaa", artist: "Vikram Montrose", album: "Shershaah", yt: "Gqnnrop26Sw" },
  { title: "Kusu Kusu", artist: "Zahrah S Khan, Dev Negi, Tanishk Bagchi", album: "Satyameva Jayate 2", yt: "aDOs442shYU" },
  { title: "Dil Galti Kar Baitha Hai", artist: "Jubin Nautiyal, Meet Bros", album: "Dil Galti Kar Baitha Hai", yt: "WCDXUgvddR4" },
  { title: "Lut Gaye", artist: "Jubin Nautiyal, Tanishk Bagchi", album: "Lut Gaye", yt: "S2BOXJG71FY" },
  { title: "Bedardi Se Pyaar Ka", artist: "Jubin Nautiyal, Meet Bros", album: "Bedardi Se Pyaar Ka", yt: "8K9eaAKLrE0" },
  { title: "Khushi Jab Bhi Teri", artist: "Jubin Nautiyal, Rochak Kohli", album: "Khushi Jab Bhi Teri", yt: "jh6Anzu3ntQ" },
  { title: "Barsaat Ki Dhun", artist: "Jubin Nautiyal, Rochak Kohli", album: "Barsaat Ki Dhun", yt: "4O0_erwpB9E" },
  { title: "Wafa Na Raas Aayee", artist: "Meet Bros, Jubin Nautiyal", album: "Wafa Na Raas Aayee", yt: "naQXI7l6op0" },
  { title: "Bewafa Tera Masoom Chehra", artist: "Jubin Nautiyal, Rochak Kohli", album: "Bewafa Tera Masoom Chehra", yt: "Kp76nzS7pwA" },
  { title: "Taaron Ke Shehar", artist: "Neha Kakkar, Jubin Nautiyal, Jaani", album: "Taaron Ke Shehar", yt: "xWi8nDUjHGA" },
  { title: "Main Jis Din Bhulaa Du", artist: "Jubin Nautiyal, Tulsi Kumar, Rochak Kohli", album: "Main Jis Din Bhulaa Du", yt: "5GCfYLguTIs" },
  { title: "Mast Nazron Se", artist: "Jubin Nautiyal, Rochak Kohli", album: "Mast Nazron Se", yt: "2sAzb3kraoQ" },
  { title: "Kuch Baatein", artist: "Jubin Nautiyal, Payal Dev", album: "Kuch Baatein", yt: "CeFQO9MQNqs" },
  { title: "O Aasman Wale", artist: "Jubin Nautiyal, Rochak Kohli", album: "O Aasman Wale", yt: "uChhQpHMmXE" },
  { title: "Kachiyaan Kachiyaan", artist: "Jubin Nautiyal, Meet Bros", album: "Kachiyaan Kachiyaan", yt: "k85UB5b6pJU" },
  { title: "Chaand Baaliyan", artist: "Aditya A", album: "Chaand Baaliyan", yt: "fRJ03btNsao" },
  { title: "Banjarey", artist: "Yo Yo Honey Singh", album: "Fugly", yt: "RuDsBrSczis" },
  { title: "Blue Eyes", artist: "Yo Yo Honey Singh", album: "Blue Eyes", yt: "4-iO6c-JmN8" },
  { title: "Desi Kalakaar", artist: "Yo Yo Honey Singh", album: "Desi Kalakaar", yt: "g6fnFALEseI" },
  { title: "Love Dose", artist: "Yo Yo Honey Singh", album: "Desi Kalakaar", yt: "W1S9AbHpWFY" },
  { title: "Dope Shope", artist: "Yo Yo Honey Singh, Deep Money", album: "International Villager", yt: "1qeujW9f4So" },
  { title: "Brown Rang", artist: "Yo Yo Honey Singh", album: "International Villager", yt: "k6GjS_Hzg8I" },
  { title: "Angreji Beat", artist: "Yo Yo Honey Singh, Gippy Grewal", album: "International Villager", yt: "PLIsDVqACZ0" },
  { title: "High Heels Te Nachche", artist: "Meet Bros, Jaz Dhami, Yo Yo Honey Singh", album: "Ki & Ka", yt: "P7yRYiBiV3g" },
  { title: "Sunny Sunny", artist: "Yo Yo Honey Singh, Neha Kakkar", album: "Yaariyan", yt: "Gqnnrop26Sw" },
  { title: "Lungi Dance", artist: "Yo Yo Honey Singh", album: "Chennai Express", yt: "aDOs442shYU" },
  { title: "Party All Night", artist: "Yo Yo Honey Singh", album: "Boss", yt: "WCDXUgvddR4" },
  { title: "Chaar Botal Vodka", artist: "Yo Yo Honey Singh", album: "Ragini MMS 2", yt: "U0H_9C9c8xU" },
  { title: "Makhna", artist: "Yo Yo Honey Singh, Neha Kakkar, Singhsta", album: "Makhna", yt: "8K9eaAKLrE0" },
  { title: "Loca", artist: "Yo Yo Honey Singh, Simar Kaur", album: "Loca", yt: "jh6Anzu3ntQ" },
  { title: "First Kiss", artist: "Yo Yo Honey Singh, Ipsitaa", album: "First Kiss", yt: "4O0_erwpB9E" },
  { title: "Saiyaan Ji", artist: "Yo Yo Honey Singh, Neha Kakkar", album: "Saiyaan Ji", yt: "naQXI7l6op0" },
  { title: "Kanta Laga", artist: "Tony Kakkar, Yo Yo Honey Singh, Neha Kakkar", album: "Kanta Laga", yt: "Kp76nzS7pwA" },
  { title: "Yai Re", artist: "Yo Yo Honey Singh, Iulia Vantur", album: "Yai Re", yt: "HasiFemale1" },
  { title: "Kudi Chamkeeli", artist: "Yo Yo Honey Singh", album: "Selfiee", yt: "YehKaisiJag" },
  { title: "Naagan", artist: "Yo Yo Honey Singh", album: "Honey 3.0", yt: "KaunHoyega1" },
  { title: "Kalaastar", artist: "Yo Yo Honey Singh, Sonakshi Sinha", album: "Honey 3.0", yt: "MannBharrya" },
  { title: "Payal", artist: "Yo Yo Honey Singh, Nora Fatehi, Paradox", album: "Glory", yt: "KaashAisaHo" },
  { title: "Millionaire", artist: "Yo Yo Honey Singh", album: "Glory", yt: "Judaiyaan01" },
  { title: "Bonita", artist: "Yo Yo Honey Singh", album: "Glory", yt: "HawaBanke02" },
  { title: "Jatt Mehkma", artist: "Yo Yo Honey Singh", album: "Glory", yt: "KabhiiTumhh" }
];
