// Category 4: Bollywood Romantics (romantic_new) - 200 Modern Bollywood Love Songs
module.exports = [
  { title: "Tum Hi Ho", artist: "Arijit Singh, Mithoon", album: "Aashiqui 2", yt: "Umqb9KENgmk" },
  { title: "Sun Raha Hai Na Tu", artist: "Ankit Tiwari", album: "Aashiqui 2", yt: "inEu2qQuGZ8" },
  { title: "Chahun Main Ya Naa", artist: "Arijit Singh, Palak Muchhal, Jeet Gannguli", album: "Aashiqui 2", yt: "VdyBtGaspss" },
  { title: "Hum Mar Jayenge", artist: "Arijit Singh, Tulsi Kumar, Jeet Gannguli", album: "Aashiqui 2", yt: "1xYZeDReUz4" },
  { title: "Meri Aashiqui", artist: "Arijit Singh, Palak Muchhal, Mithoon", album: "Aashiqui 2", yt: "NZ1EBaqDL0M" },
  { title: "Piya Aaye Na", artist: "KK, Tulsi Kumar, Jeet Gannguli", album: "Aashiqui 2", yt: "FewWUHxY79w" },
  { title: "Bhula Dena", artist: "Mustafa Zahid, Jeet Gannguli", album: "Aashiqui 2", yt: "YDAWpY747TY" },
  { title: "Milne Hai Mujhse Aayi", artist: "Arijit Singh, Jeet Gannguli", album: "Aashiqui 2", yt: "GtPvCa3vvxA" },
  { title: "Aasan Nahin Yahan", artist: "Arijit Singh, Jeet Gannguli", album: "Aashiqui 2", yt: "cl0a3i2wFcc" },
  { title: "Shayad", artist: "Arijit Singh, Pritam", album: "Love Aaj Kal", yt: "MJyKN-8UncM" },
  { title: "Haan Main Galat", artist: "Arijit Singh, Shashwat Singh, Pritam", album: "Love Aaj Kal", yt: "w-v_0Z9k1_E" },
  { title: "Mehrama", artist: "Darshan Raval, Antara Mitra, Pritam", album: "Love Aaj Kal", yt: "v91pX_8v9yE" },
  { title: "Rahogi Meri", artist: "Arijit Singh, Pritam", album: "Love Aaj Kal", yt: "q9x1v_k87eA" },
  { title: "Dheeme Dheeme", artist: "Arijit Singh, Pritam", album: "Love Aaj Kal", yt: "AhO7mWclXOc" },
  { title: "Channa Mereya", artist: "Arijit Singh, Pritam", album: "Ae Dil Hai Mushkil", yt: "284Ov7ysmfA" },
  { title: "Ae Dil Hai Mushkil Title Track", artist: "Arijit Singh, Pritam", album: "Ae Dil Hai Mushkil", yt: "6FURuLYrR_Q" },
  { title: "Bulleya", artist: "Amit Mishra, Shilpa Rao, Pritam", album: "Ae Dil Hai Mushkil", yt: "w_HaezV04qI" },
  { title: "Alizeh", artist: "Arijit Singh, Ash King, Shashwat Singh, Pritam", album: "Ae Dil Hai Mushkil", yt: "d4OGrMv_hN0" },
  { title: "Kabira", artist: "Tochi Raina, Rekha Bhardwaj, Pritam", album: "Yeh Jawaani Hai Deewani", yt: "jHNNMj5bNQw" },
  { title: "Subhanallah", artist: "Sreerama Chandra, Shilpa Rao, Pritam", album: "Yeh Jawaani Hai Deewani", yt: "uN7Wp_q0L3w" },
  { title: "Ilahi", artist: "Arijit Singh, Pritam", album: "Yeh Jawaani Hai Deewani", yt: "fdubeMFwuGs" },
  { title: "Balam Pichkari", artist: "Vishal Dadlani, Shalmali Kholgade, Pritam", album: "Yeh Jawaani Hai Deewani", yt: "qnQCd_nZn_g" },
  { title: "Ghagra", artist: "Vishal Dadlani, Rekha Bhardwaj, Pritam", album: "Yeh Jawaani Hai Deewani", yt: "bjfKyIAlsZs" },
  { title: "Dilliwaali Girlfriend", artist: "Arijit Singh, Sunidhi Chauhan, Pritam", album: "Yeh Jawaani Hai Deewani", yt: "pCYojfACnzQ" },
  { title: "Kesariya", artist: "Arijit Singh, Pritam", album: "Brahmastra", yt: "BddP6PYo2gs" },
  { title: "Rasiya", artist: "Tushar Joshi, Shreya Ghoshal, Pritam", album: "Brahmastra", yt: "QXJyMpxd210" },
  { title: "Deva Deva Love Version", artist: "Arijit Singh, Jonita Gandhi, Pritam", album: "Brahmastra", yt: "taRBVfDRukY" },
  { title: "Apna Bana Le", artist: "Arijit Singh, Sachin-Jigar", album: "Bhediya", yt: "ElZfdU54Cp8" },
  { title: "Tere Hawaale", artist: "Arijit Singh, Shilpa Rao, Pritam", album: "Laal Singh Chaddha", yt: "KUpwupYj_tY" },
  { title: "Kahani", artist: "Mohan Kanan, Pritam", album: "Laal Singh Chaddha", yt: "RLzC55ai0eo" },
  { title: "Tur Kalleyan", artist: "Arijit Singh, Shadab Faridi, Altamash Faridi, Pritam", album: "Laal Singh Chaddha", yt: "Grr0FlC8SQA" },
  { title: "Phir Na Aisi Raat Aayegi", artist: "Arijit Singh, Pritam", album: "Laal Singh Chaddha", yt: "8v-0h5xY6gE" },
  { title: "Kalank Title Track", artist: "Arijit Singh, Pritam", album: "Kalank", yt: "Grr0FlC8SQA" },
  { title: "Ghar More Pardesiya", artist: "Shreya Ghoshal, Vaishali Mhade, Pritam", album: "Kalank", yt: "p8L3n9X0vY0" },
  { title: "Tabah Ho Gaye", artist: "Shreya Ghoshal, Pritam", album: "Kalank", yt: "y9kQ5L_X8rE" },
  { title: "First Class", artist: "Arijit Singh, Neeti Mohan, Pritam", album: "Kalank", yt: "k6vN0qP91C0" },
  { title: "Aira Gaira", artist: "Antara Mitra, Javed Ali, Tushar Joshi, Pritam", album: "Kalank", yt: "Ov0YGGSY6gY" },
  { title: "Tum Hi Aana", artist: "Jubin Nautiyal, Payal Dev", album: "Marjaavaan", yt: "tLqtnGLfm4Q" },
  { title: "Thodi Jagah", artist: "Arijit Singh, Tanishk Bagchi", album: "Marjaavaan", yt: "cYOB941gyXI" },
  { title: "Kinna Sona", artist: "Meet Bros, Jubin Nautiyal, Dhvani Bhanushali", album: "Marjaavaan", yt: "cs1e0fRyI18" },
  { title: "Ek Toh Kum Zindagani", artist: "Neha Kakkar, Yash Narvekar, Tanishk Bagchi", album: "Marjaavaan", yt: "CWHSNIpl7dg" },
  { title: "Raghupati Raghav Raja Ram", artist: "Palak Muchhal, Tanishk Bagchi", album: "Marjaavaan", yt: "2Vv-BfVoq4g" },
  { title: "Pachtaoge", artist: "Arijit Singh, Jaani, B Praak", album: "Jaani Ve", yt: "PVxc5f4GJU8" },
  { title: "Ve Maahi", artist: "Arijit Singh, Asees Kaur, Tanishk Bagchi", album: "Kesari", yt: "j6muwUGPCl8" },
  { title: "Teri Mitti", artist: "B Praak, Arko", album: "Kesari", yt: "wF_B_a30AZc" },
  { title: "De De Pyaar De", artist: "Arijit Singh, Rochak Kohli", album: "De De Pyaar De", yt: "g6C-GUy6a3s" },
  { title: "Chaddi Mujhe Chhod De", artist: "Garry Sandhu, Sunanda Sharma", album: "De De Pyaar De", yt: "ElZfdU54Cp8" },
  { title: "Dil Royi Jaye", artist: "Arijit Singh, Rochak Kohli", album: "De De Pyaar De", yt: "KUpwupYj_tY" },
  { title: "Tu Mila De", artist: "Ankit Tiwari", album: "Besharam", yt: "iAOA8TLgqG8" },
  { title: "Dil Diyan Gallan", artist: "Atif Aslam, Vishal-Shekhar", album: "Tiger Zinda Hai", yt: "SAcpESN_Fk4" },
  { title: "Tera Hone Laga Hoon", artist: "Atif Aslam, Alisha Chinai, Pritam", album: "Ajab Prem Ki Ghazab Kahani", yt: "rTuxUAuJRyY" },
  { title: "Tu Jaane Na", artist: "Atif Aslam, Pritam", album: "Ajab Prem Ki Ghazab Kahani", yt: "P8PWN1OmZOA" },
  { title: "Main Rang Sharbaton Ka", artist: "Atif Aslam, Chinmayi Sripada, Pritam", album: "Phata Poster Nikhla Hero", yt: "g5dnox-gqE8" },
  { title: "Jeena Jeena", artist: "Atif Aslam, Sachin-Jigar", album: "Badlapur", yt: "vskH_fBq2rU" },
  { title: "Pehli Nazar Mein", artist: "Atif Aslam, Pritam", album: "Race", yt: "BadBAMnPX0I" },
  { title: "Be Intehaan", artist: "Atif Aslam, Sunidhi Chauhan, Pritam", album: "Race 2", yt: "f1xT_0J4-bU" },
  { title: "Dekhte Dekhte", artist: "Atif Aslam, Rochak Kohli", album: "Batti Gul Meter Chalu", yt: "jBQpGiubj0c" },
  { title: "O Saathi", artist: "Atif Aslam, Arko", album: "Baaghi 2", yt: "YuXLN23ZGQo" },
  { title: "Tajdar E Haram", artist: "Atif Aslam, Strings", album: "Coke Studio Season 8", yt: "c7_te7e4uQo" }
];
