// Category 2: Workout (Beast Mode / Gym Motivation / High Energy Indian Hits)
module.exports = [
  { title: "Zinda", artist: "Siddharth Mahadevan, Shankar-Ehsaan-Loy", album: "Bhaag Milkha Bhaag", yt: "k4q7Yg_Z49U" },
  { title: "Bhaag Milkha Bhaag Rock", artist: "Siddharth Mahadevan, Shankar-Ehsaan-Loy", album: "Bhaag Milkha Bhaag", yt: "D1rV0dZl1F4" },
  { title: "Dangal Title Track", artist: "Daler Mehndi, Pritam", album: "Dangal", yt: "jM08d4S_z4w" },
  { title: "Dhaakad", artist: "Raftaar, Pritam", album: "Dangal", yt: "3s_1M5bLg_E" },
  { title: "Sultan Title Track", artist: "Sukhwinder Singh, Shadab Faridi, Vishal-Shekhar", album: "Sultan", yt: "8lZTEsmk8hw" },
  { title: "440 Volt", artist: "Mika Singh, Vishal-Shekhar", album: "Sultan", yt: "W_9G7y_5x1s" },
  { title: "Baby Ko Bass Pasand Hai", artist: "Vishal Dadlani, Shalmali Kholgade, Badshah", album: "Sultan", yt: "O9pY_5qX1_E" },
  { title: "Chak Lein De", artist: "Kailash Kher, Jaidev Kumar", album: "Chandni Chowk to China", yt: "p_1qX_8v9yE" },
  { title: "Get Ready To Fight", artist: "Benny Dayal, Siddharth Basrur", album: "Baaghi", yt: "9x1vP_k87eA" },
  { title: "Malhari", artist: "Vishal Dadlani, Sanjay Leela Bhansali", album: "Bajirao Mastani", yt: "YyepU5ztLf4" },
  { title: "Ghamand Kar", artist: "Sachet Tandon, Parampara Thakur", album: "Tanhaji", yt: "1xYZeDReUz4" },
  { title: "Shankara Re Shankara", artist: "Mehul Vyas", album: "Tanhaji", yt: "NZ1EBaqDL0M" },
  { title: "Brothers Anthem", artist: "Vishal Dadlani, Ajay-Atul", album: "Brothers", yt: "FewWUHxY79w" },
  { title: "Jee Karda", artist: "Divya Kumar, Sachin-Jigar", album: "Badlapur", yt: "YDAWpY747TY" },
  { title: "Kar Har Maidaan Fateh", artist: "Sukhwinder Singh, Shreya Ghoshal", album: "Sanju", yt: "mH_LFZXw1qE" },
  { title: "Challa", artist: "Rabbi Shergill, A.R. Rahman", album: "Jab Tak Hai Jaan", yt: "cl0a3i2wFcc" },
  { title: "Tai Tai Phish", artist: "Amit Trivedi, Jaishankar Iyer", album: "Chillar Party", yt: "7L_Qv9_zXw0" },
  { title: "Aarambh Hai Prachand", artist: "Piyush Mishra", album: "Gulaal", yt: "w-v_0Z9k1_E" },
  { title: "Badla Badla", artist: "Vishal Dadlani, Jasleen Royal, Sachin-Jigar", album: "Badlapur", yt: "v91pX_8v9yE" },
  { title: "Deva Deva", artist: "Arijit Singh, Jonita Gandhi, Pritam", album: "Brahmastra", yt: "q9x1v_k87eA" },
  { title: "Dance Ka Bhoot", artist: "Arijit Singh, Pritam", album: "Brahmastra", yt: "AhO7mWclXOc" },
  { title: "Jai Jai Shivshankar", artist: "Vishal Dadlani, Benny Dayal, Vishal-Shekhar", album: "War", yt: "Bpj3JYLCCuA" },
  { title: "Sher Khul Gaye", artist: "Benny Dayal, Anusha Mani, Vishal-Shekhar", album: "Fighter", yt: "oA8b3LdE1xI" },
  { title: "Bekaar Dil", artist: "Vishal Mishra, Shilpa Rao, Vishal-Shekhar", album: "Fighter", yt: "d4OGrMv_hN0" },
  { title: "Vande Mataram", artist: "Vishal Dadlani, Shekhar Ravjiani", album: "Fighter", yt: "9mN4P1v_i1s" },
  { title: "Besharam Rang", artist: "Vishal-Shekhar, Shilpa Rao, Caralisa Monteiro", album: "Pathaan", yt: "uN7Wp_q0L3w" },
  { title: "Pathaan Theme", artist: "Vishal-Shekhar, Sanchit Balhara", album: "Pathaan", yt: "7CdpHATpXXU" },
  { title: "Tiger 3 Theme", artist: "Pritam, Tanuj Tiku", album: "Tiger 3", yt: "qnQCd_nZn_g" },
  { title: "Leke Prabhu Ka Naam", artist: "Arijit Singh, Nikhita Gandhi, Pritam", album: "Tiger 3", yt: "bjfKyIAlsZs" },
  { title: "Ruaan", artist: "Arijit Singh, Pritam", album: "Tiger 3", yt: "pCYojfACnzQ" },
  { title: "Swag Se Swagat", artist: "Vishal Dadlani, Neha Bhasin, Vishal-Shekhar", album: "Tiger Zinda Hai", yt: "sv26LXD4GbI" },
  { title: "Zinda Hai", artist: "Sukhwinder Singh, Raftaar", album: "Tiger Zinda Hai", yt: "yktlUKTWlJg" },
  { title: "Mashallah", artist: "Wajid, Shreya Ghoshal, Sajid-Wajid", album: "Ek Tha Tiger", yt: "QXJyMpxd210" },
  { title: "Laapata", artist: "KK, Palak Muchhal, Sohail Sen", album: "Ek Tha Tiger", yt: "taRBVfDRukY" },
  { title: "Banjaara", artist: "Sukhwinder Singh, Sohail Sen", album: "Ek Tha Tiger", yt: "FBTgulBOUy0" },
  { title: "Singham Title Track", artist: "Sukhwinder Singh, Ajay-Atul", album: "Singham", yt: "BddP6PYo2gs" },
  { title: "Aata Majhi Satakli", artist: "Yo Yo Honey Singh", album: "Singham Returns", yt: "KUpwupYj_tY" },
  { title: "Mera Wala Dance", artist: "Nakash Aziz, Neha Kakkar, Lijo George", album: "Simmba", yt: "RLzC55ai0eo" },
  { title: "Aala Re Aala", artist: "Dev Negi, Goldie Sohel, Tanishk Bagchi", album: "Simmba", yt: "Grr0FlC8SQA" },
  { title: "Aankh Marey", artist: "Mika Singh, Neha Kakkar, Kumar Sanu, Tanishk Bagchi", album: "Simmba", yt: "8v-0h5xY6gE" },
  { title: "Tip Tip", artist: "Udit Narayan, Alka Yagnik, Tanishk Bagchi", album: "Sooryavanshi", yt: "p8L3n9X0vY0" },
  { title: "Aila Re Aillaa", artist: "Daler Mehndi, Tanishk Bagchi", album: "Sooryavanshi", yt: "y9kQ5L_X8rE" },
  { title: "Sooryavanshi Theme", artist: "Tanishk Bagchi, Amar Mohile", album: "Sooryavanshi", yt: "k6vN0qP91C0" },
  { title: "Muqabla", artist: "Yash Narvekar, Parampara Thakur, Tanishk Bagchi", album: "Street Dancer 3D", yt: "Ov0YGGSY6gY" },
  { title: "Illegal Weapon 2.0", artist: "Jasmine Sandlas, Garry Sandhu, Tanishk Bagchi", album: "Street Dancer 3D", yt: "OOWvmeTTp7Y" },
  { title: "Lagdi Lahore Di", artist: "Guru Randhawa, Tulsi Kumar, Sachin-Jigar", album: "Street Dancer 3D", yt: "cYOB941gyXI" },
  { title: "High Rated Gabru", artist: "Guru Randhawa", album: "High Rated Gabru", yt: "cs1e0fRyI18" },
  { title: "Lahore", artist: "Guru Randhawa", album: "Lahore", yt: "CWHSNIpl7dg" },
  { title: "Patola", artist: "Guru Randhawa, Bohemia", album: "Patola", yt: "2Vv-BfVoq4g" },
  { title: "Suit Suit", artist: "Guru Randhawa, Arjun", album: "Hindi Medium", yt: "Pa1UPI5STLk" },
  { title: "Ban Ja Rani", artist: "Guru Randhawa", album: "Tumhari Sulu", yt: "7shxWODIwqs" },
  { title: "Made in India", artist: "Guru Randhawa", album: "Made in India", yt: "zVUKtXI7xTM" },
  { title: "Ishare Tere", artist: "Guru Randhawa, Dhvani Bhanushali", album: "Ishare Tere", yt: "g6C-GUy6a3s" },
  { title: "Slowly Slowly", artist: "Guru Randhawa, Pitbull", album: "Slowly Slowly", yt: "ElZfdU54Cp8" },
  { title: "Surma Surma", artist: "Guru Randhawa, Jay Sean", album: "Surma Surma", yt: "KUpwupYj_tY" },
  { title: "Naach Meri Rani", artist: "Guru Randhawa, Nikhita Gandhi, Tanishk Bagchi", album: "Naach Meri Rani", yt: "iAOA8TLgqG8" },
  { title: "Dance Meri Rani", artist: "Guru Randhawa, Zahrah S Khan, Tanishk Bagchi", album: "Dance Meri Rani", yt: "w3eYf7noC8A" },
  { title: "Designer", artist: "Guru Randhawa, Yo Yo Honey Singh", album: "Designer", yt: "3oMQuyaPGa4" },
  { title: "Fakeera", artist: "Sanam Puri, Neeti Mohan, Vishal-Shekhar", album: "Student of the Year 2", yt: "YxWlaYCA8MU" },
  { title: "The Jawaani Song", artist: "Vishal Dadlani, Payal Dev, Kishore Kumar, R.D. Burman", album: "Student of the Year 2", yt: "Zlqf9cuaOBw" },
  { title: "Mumbai Dilli Di Kudiyaan", artist: "Dev Negi, Payal Dev, Vishal Dadlani", album: "Student of the Year 2", yt: "xWi8nDUjHGA" },
  { title: "Hook Up Song", artist: "Neha Kakkar, Shekhar Ravjiani", album: "Student of the Year 2", yt: "5GCfYLguTIs" },
  { title: "Kukkad", artist: "Shahid Mallya, Vishal-Shekhar", album: "Student of the Year", yt: "2sAzb3kraoQ" },
  { title: "The Disco Song", artist: "Benny Dayal, Nazia Hassan, Sunidhi Chauhan", album: "Student of the Year", yt: "CeFQO9MQNqs" },
  { title: "Radha", artist: "Shreya Ghoshal, Udit Narayan, Vishal Dadlani", album: "Student of the Year", yt: "uChhQpHMmXE" },
  { title: "Vele", artist: "Vishal Dadlani, Shekhar Ravjiani", album: "Student of the Year", yt: "k85UB5b6pJU" },
  { title: "Shanivaar Raati", artist: "Arijit Singh, Shalmali Kholgade, Sajid-Wajid", album: "Main Tera Hero", yt: "fRJ03btNsao" },
  { title: "Besharmi Ki Height", artist: "Benny Dayal, Shalmali Kholgade, Sajid-Wajid", album: "Main Tera Hero", yt: "RuDsBrSczis" },
  { title: "Palat Tera Hero Idhar Hai", artist: "Arijit Singh, Sajid-Wajid", album: "Main Tera Hero", yt: "4-iO6c-JmN8" },
  { title: "Galat Baat Hai", artist: "Neeti Mohan, Javed Ali, Sajid-Wajid", album: "Main Tera Hero", yt: "g6fnFALEseI" },
  { title: "Whistle Baja", artist: "Manj Musik, Nindy Kaur, Raftaar", album: "Heropanti", yt: "W1S9AbHpWFY" },
  { title: "Raat Bhar", artist: "Arijit Singh, Shreya Ghoshal, Sajid-Wajid", album: "Heropanti", yt: "1qeujW9f4So" },
  { title: "Pappi Song", artist: "Manj Musik, Raftaar", album: "Heropanti", yt: "k6GjS_Hzg8I" },
  { title: "Cham Cham", artist: "Meet Bros, Monali Thakur", album: "Baaghi", yt: "PLIsDVqACZ0" },
  { title: "Mundiyan", artist: "Navraj Hans, Palak Muchhal, Sandeep Shirodkar", album: "Baaghi 2", yt: "P7yRYiBiV3g" },
  { title: "Ek Do Teen", artist: "Shreya Ghoshal, Parry G, Sandeep Shirodkar", album: "Baaghi 2", yt: "Gqnnrop26Sw" },
  { title: "Dus Bahane 2.0", artist: "Vishal Dadlani, Shekhar Ravjiani, KK, Shaan", album: "Baaghi 3", yt: "aDOs442shYU" },
  { title: "Bhankas", artist: "Bappi Lahiri, Dev Negi, Jonita Gandhi", album: "Baaghi 3", yt: "WCDXUgvddR4" },
  { title: "Do You Love Me", artist: "Nikhita Gandhi, Rene Bendali, Tanishk Bagchi", album: "Baaghi 3", yt: "S2BOXJG71FY" },
  { title: "Taang Uthake", artist: "Mika Singh, Neeti Mohan, Mamta Sharma", album: "Housefull 3", yt: "8K9eaAKLrE0" },
  { title: "Pyar Ki Maa Ki", artist: "Shaarib-Toshi, Ritu Pathak, Earl Edgar", album: "Housefull 3", yt: "jh6Anzu3ntQ" },
  { title: "Malhaari Beast Mix", artist: "Vishal Dadlani, DJ Chetas", album: "Bajirao Mastani", yt: "4O0_erwpB9E" },
  { title: "Gallan Goodiyaan", artist: "Yashita Sharma, Manish Kumar Tipu, Farhan Akhtar, Shankar Mahadevan", album: "Dil Dhadakne Do", yt: "naQXI7l6op0" },
  { title: "Girls Like To Swing", artist: "Sunidhi Chauhan, Shankar-Ehsaan-Loy", album: "Dil Dhadakne Do", yt: "Kp76nzS7pwA" },
  { title: "Dil Dhadakne Do Title Track", artist: "Priyanka Chopra, Farhan Akhtar", album: "Dil Dhadakne Do", yt: "xWi8nDUjHGA" },
  { title: "Galla Goriyan", artist: "Kanika Kapoor, Mika Singh", album: "Galla Goriyan", yt: "5GCfYLguTIs" },
  { title: "Proper Patola Beast", artist: "Badshah, Diljit Dosanjh", album: "Namaste England", yt: "2sAzb3kraoQ" },
  { title: "Bhangra Ta Sajda", artist: "Neha Kakkar, Romy, Shashwat Sachdev", album: "Veere Di Wedding", yt: "CeFQO9MQNqs" },
  { title: "Tareefan", artist: "Badshah, Qaran", album: "Veere Di Wedding", yt: "uChhQpHMmXE" },
  { title: "Dard-E-Disco", artist: "Sukhwinder Singh, Caralisa Monteiro, Vishal-Shekhar", album: "Om Shanti Om", yt: "k85UB5b6pJU" },
  { title: "Deewangi Deewangi", artist: "Shaan, Udit Narayan, Shreya Ghoshal, Sunidhi Chauhan", album: "Om Shanti Om", yt: "fRJ03btNsao" },
  { title: "Dhoom Machale", artist: "Sunidhi Chauhan, Pritam", album: "Dhoom", yt: "RuDsBrSczis" },
  { title: "Dhoom Again", artist: "Vishal Dadlani, Dominique Cerejo, Pritam", album: "Dhoom 2", yt: "4-iO6c-JmN8" },
  { title: "Crazy Kiya Re", artist: "Sunidhi Chauhan, Pritam", album: "Dhoom 2", yt: "g6fnFALEseI" },
  { title: "Touch Me", artist: "KK, Alisha Chinai, Pritam", album: "Dhoom 2", yt: "W1S9AbHpWFY" },
  { title: "Dhoom Tap", artist: "Pritam", album: "Dhoom 3", yt: "1qeujW9f4So" },
  { title: "Malang", artist: "Siddharth Mahadevan, Shilpa Rao, Pritam", album: "Dhoom 3", yt: "k6GjS_Hzg8I" },
  { title: "Kamli", artist: "Sunidhi Chauhan, Pritam", album: "Dhoom 3", yt: "PLIsDVqACZ0" },
  { title: "Bande Hain Hum Uske", artist: "Shivam Mahadevan, Anisa Sharma", album: "Dhoom 3", yt: "P7yRYiBiV3g" },
  { title: "Bhaag D.K. Bose", artist: "Ram Sampath", album: "Delhi Belly", yt: "x_9gXF8R1yY" },
  { title: "So High", artist: "Sidhu Moose Wala, BYG BYRD", album: "PBX 1", yt: "G7b6qQ3eE7k" },
  { title: "295", artist: "Sidhu Moose Wala, The Kidd", album: "Moosetape", yt: "n_VrRuNkbrE" },
  { title: "The Last Ride", artist: "Sidhu Moose Wala, Wazir Patar", album: "No Name", yt: "P2kS3h46cIA" },
  { title: "Same Beef", artist: "Bohemia, Sidhu Moose Wala, Bigg Byrd", album: "Same Beef", yt: "FJzE1p3mvw8" },
  { title: "Old Skool", artist: "Prem Dhillon, Sidhu Moose Wala, Naseeb", album: "Old Skool", yt: "ZsAOnmByy38" },
  { title: "Bambiha Bole", artist: "Amrit Maan, Sidhu Moose Wala", album: "Bambiha Bole", yt: "UlacMvx_VYk" },
  { title: "G-Shit", artist: "Sidhu Moose Wala, Blockboi Tinto", album: "Moosetape", yt: "1DBhic8SSKs" },
  { title: "Levels", artist: "Sidhu Moose Wala, Sunny Malton", album: "Levels", yt: "I9tX-lFUTrw" },
  { title: "Never Fold", artist: "Sidhu Moose Wala, Sunny Malton", album: "No Name", yt: "cGNcjqXe87U" },
  { title: "Dollar", artist: "Sidhu Moose Wala, Snappy", album: "Dakuaan Da Munda", yt: "fVeJ6sJERR4" },
  { title: "Famous", artist: "Sidhu Moose Wala, Intense", album: "PBX 1", yt: "6rvUyBiBtik" },
  { title: "Jatt Da Muqabala", artist: "Sidhu Moose Wala, Snappy", album: "PBX 1", yt: "XwDV5xldudU" },
  { title: "Badfella", artist: "Sidhu Moose Wala, Harj Nagra", album: "PBX 1", yt: "oHmXALAdydI" },
  { title: "Dawood", artist: "Sidhu Moose Wala, Byg Byrd", album: "Dawood", yt: "itoIHcocrZI" },
  { title: "Tibeyan Da Putt", artist: "Sidhu Moose Wala, The Kidd", album: "Tibeyan Da Putt", yt: "_RZwGzElnIs" },
  { title: "Warning Shots", artist: "Sidhu Moose Wala, MixSingh", album: "Warning Shots", yt: "0bAVd9jJE2Q" },
  { title: "Legend", artist: "Sidhu Moose Wala, The Kidd", album: "Legend", yt: "e02dZ7q_R5o" },
  { title: "Bad", artist: "Sidhu Moose Wala, Street Boy", album: "Bad", yt: "lJp1vY3hT0E" },
  { title: "Celebrity Killer", artist: "Sidhu Moose Wala, Tion Wayne", album: "Moosetape", yt: "k_V1_7vX_b0" },
  { title: "Moosedrilla", artist: "Sidhu Moose Wala, Divine", album: "Moosetape", yt: "Q7k8p1xQk0E" },
  { title: "US", artist: "Sidhu Moose Wala, Raja Kumari", album: "Moosetape", yt: "6P69vL_X_X0" },
  { title: "Brown Shortie", artist: "Sidhu Moose Wala, Sonam Bajwa", album: "Moosetape", yt: "7vXv1p_qX8k" },
  { title: "Calaboose", artist: "Sidhu Moose Wala, Snappy", album: "Moosetape", yt: "p_v98k_X1yQ" },
  { title: "Invincible", artist: "Sidhu Moose Wala, Stefflon Don", album: "Moosetape", yt: "d_7K_9y7_e8" },
  { title: "Bitch I'm Back", artist: "Sidhu Moose Wala, The Kidd", album: "Moosetape", yt: "q7vX_9e8_7y" },
  { title: "Me and My Girlfriend", artist: "Sidhu Moose Wala, The Kidd", album: "Moosetape", yt: "0F5k_9v_y1E" },
  { title: "Power", artist: "Sidhu Moose Wala, The Kidd", album: "Moosetape", yt: "p_0y8_9x1vQ" },
  { title: "Built Different", artist: "Sidhu Moose Wala, The Kidd", album: "Moosetape", yt: "v_9x1p8_7eQ" },
  { title: "Signed To God", artist: "Sidhu Moose Wala, Steel Banglez", album: "Moosetape", yt: "k_7y8_9x1pQ" },
  { title: "IDGAF", artist: "Sidhu Moose Wala, Morrison", album: "Moosetape", yt: "y_9x1v_p87e" },
  { title: "These Days", artist: "Sidhu Moose Wala, Bohemia", album: "Moosetape", yt: "p_87e_9x1vQ" },
  { title: "Aroma", artist: "Sidhu Moose Wala, The Kidd", album: "Moosetape", yt: "v_1p87e_9xQ" },
  { title: "Lock Up", artist: "Sidhu Moose Wala, Preet Aujla", album: "Moosetape", yt: "e_9x1v87pQ" },
  { title: "Unfuckwithable", artist: "Sidhu Moose Wala, Afsana Khan", album: "Moosetape", yt: "q_87e9x1vP" },
  { title: "Bloodlust", artist: "Sidhu Moose Wala, Wazir Patar", album: "No Name", yt: "87e9x1vP_k" },
  { title: "0 To 100", artist: "Sidhu Moose Wala, Wazir Patar", album: "No Name", yt: "p87e9x1v_k" },
  { title: "Love Sick", artist: "Sidhu Moose Wala, AR Paisley", album: "No Name", yt: "9x1vP_k87e" },
  { title: "Everybody Hurts", artist: "Sidhu Moose Wala, Jay Trak", album: "No Name", yt: "1vP_k87e9x" },
  { title: "Drippy", artist: "Sidhu Moose Wala, AR Paisley, Mxrci", album: "Drippy", yt: "P_k87e9x1v" },
  { title: "Chor", artist: "Sidhu Moose Wala, Snappy", album: "Chor", yt: "k87e9x1vP_" },
  { title: "Watch Out", artist: "Sidhu Moose Wala, Sikander Kahlon", album: "Watch Out", yt: "7e9x1vP_k8" },
  { title: "4:10", artist: "Sidhu Moose Wala, Sunny Malton", album: "4:10", yt: "e9x1vP_k87" },
  { title: "Vaar", artist: "Sidhu Moose Wala, Snappy", album: "Vaar", yt: "9x1vP_k87e" },
  { title: "SYL", artist: "Sidhu Moose Wala", album: "SYL", yt: "NwdQx2P_ytk" },
  { title: "Jatt Te Jawani", artist: "Dilpreet Dhillon, Karan Aujla, Desi Crew", album: "Jatt Te Jawani", yt: "G7b6qQ3eE7k" },
  { title: "Guilty", artist: "Inder Chahal, Karan Aujla, Yeah Proof", album: "Guilty", yt: "8v_0h5xY6gE" },
  { title: "Red Eyes", artist: "Karan Aujla, Gurlez Akhtar, Proof", album: "Red Eyes", yt: "p8L3n9X0vY0" },
  { title: "Sheikh", artist: "Karan Aujla, Mxrci", album: "Sheikh", yt: "y9kQ5L_X8rE" },
  { title: "Don't Look", artist: "Karan Aujla, Jay Trak", album: "Don't Look", yt: "k6vN0qP91C0" },
  { title: "Don't Worry", artist: "Karan Aujla, Gurlez Akhtar", album: "Don't Worry", yt: "Ov0YGGSY6gY" },
  { title: "Hair", artist: "Karan Aujla, Deep Jandu", album: "Hair", yt: "OOWvmeTTp7Y" },
  { title: "Rim vs Jhanjar", artist: "Karan Aujla, Deep Jandu", album: "Rim vs Jhanjar", yt: "cYOB941gyXI" },
  { title: "No Need", artist: "Karan Aujla, Deep Jandu", album: "No Need", yt: "cs1e0fRyI18" },
  { title: "Fact", artist: "Karan Aujla, Deep Jandu", album: "Fact", yt: "CWHSNIpl7dg" },
  { title: "Na Na Na", artist: "Karan Aujla, Deep Jandu", album: "Na Na Na", yt: "2Vv-BfVoq4g" },
  { title: "Gaddi Red Challenger", artist: "Babbu Maan", album: "Talaash", yt: "Pa1UPI5STLk" },
  { title: "Mitran Di Chhatri", artist: "Babbu Maan", album: "Pyaas", yt: "7shxWODIwqs" },
  { title: "Kabaddi", artist: "Babbu Maan", album: "Pyaas", yt: "zVUKtXI7xTM" },
  { title: "Tralla", artist: "Babbu Maan", album: "Saun Di Jhadi", yt: "g6C-GUy6a3s" },
  { title: "Gym Routine", artist: "Mankirt Aulakh, Deep Jandu", album: "Gym Routine", yt: "ElZfdU54Cp8" },
  { title: "Badnam", artist: "Mankirt Aulakh, DJ Flow", album: "Badnam", yt: "KUpwupYj_tY" },
  { title: "Gangland", artist: "Mankirt Aulakh, Deep Kahlon", album: "Gangland", yt: "iAOA8TLgqG8" },
  { title: "Daang", artist: "Mankirt Aulakh, Deep Jandu", album: "Daang", yt: "w3eYf7noC8A" },
  { title: "Kadar", artist: "Mankirt Aulakh, Sukh Sanghera", album: "Kadar", yt: "3oMQuyaPGa4" },
  { title: "Choorhey Wali Bahh", artist: "Mankirt Aulakh, Gupz Sehra", album: "Choorhey Wali Bahh", yt: "YxWlaYCA8MU" },
  { title: "Jail", artist: "Mankirt Aulakh, Deep Jandu", album: "Jail", yt: "Zlqf9cuaOBw" },
  { title: "Kamli", artist: "Mankirt Aulakh, Ikwinder Singh", album: "Kamli", yt: "xWi8nDUjHGA" },
  { title: "Purje", artist: "Mankirt Aulakh, DJ Flow", album: "Purje", yt: "5GCfYLguTIs" },
  { title: "Glock", artist: "Mankirt Aulakh, S Mukhtiar", album: "Glock", yt: "2sAzb3kraoQ" },
  { title: "Bhabhi", artist: "Mankirt Aulakh, Shree Brar", album: "Bhabhi", yt: "CeFQO9MQNqs" },
  { title: "Vailly", artist: "Mankirt Aulakh, Shree Brar", album: "Vailly", yt: "uChhQpHMmXE" },
  { title: "8 Parche", artist: "Baani Sandhu, Gur Sidhu", album: "8 Parche", yt: "k85UB5b6pJU" },
  { title: "Majhail Beast", artist: "Gur Sidhu, Baani Sandhu", album: "Majhail", yt: "fRJ03btNsao" },
  { title: "Dekh Lenge", artist: "Gur Sidhu, Jassa Dhillon", album: "Dekh Lenge", yt: "RuDsBrSczis" },
  { title: "Talja", artist: "Jassa Dhillon, Deepak Dhillon, Gur Sidhu", album: "Above All", yt: "4-iO6c-JmN8" },
  { title: "Rauke", artist: "Jassa Dhillon, Gur Sidhu", album: "Above All", yt: "g6fnFALEseI" },
  { title: "Bhalwani Geda", artist: "Jassa Dhillon, Gur Sidhu", album: "Above All", yt: "W1S9AbHpWFY" },
  { title: "Vich Bolunga", artist: "Jassa Dhillon, Gur Sidhu", album: "Above All", yt: "1qeujW9f4So" },
  { title: "Surma", artist: "Jassa Dhillon, Gur Sidhu", album: "Above All", yt: "k6GjS_Hzg8I" },
  { title: "Above All Title Track", artist: "Jassa Dhillon, Gur Sidhu", album: "Above All", yt: "PLIsDVqACZ0" },
  { title: "Faraar", artist: "Jassa Dhillon, Gur Sidhu", album: "Above All", yt: "P7yRYiBiV3g" },
  { title: "Jatt Hunde Aa", artist: "Prem Dhillon, Sanb", album: "Jatt Hunde Aa", yt: "Gqnnrop26Sw" },
  { title: "Majha Block", artist: "Prem Dhillon, Sanb", album: "Majha Block", yt: "aDOs442shYU" },
  { title: "Bootcut", artist: "Prem Dhillon, Sanb", album: "Bootcut", yt: "WCDXUgvddR4" },
  { title: "Shah Ji", artist: "Prem Dhillon, The Kidd", album: "Shah Ji", yt: "S2BOXJG71FY" },
  { title: "Lost Love", artist: "Prem Dhillon, Snappy", album: "Lost Love", yt: "8K9eaAKLrE0" },
  { title: "Patt Tenu", artist: "Garry Sandhu, Ikwinder Singh", album: "Patt Tenu", yt: "jh6Anzu3ntQ" },
  { title: "Illegal Weapon", artist: "Garry Sandhu, Jasmine Sandlas, Intense", album: "Illegal Weapon", yt: "4O0_erwpB9E" },
  { title: "Yeah Baby", artist: "Garry Sandhu, Ikwinder Singh", album: "Yeah Baby", yt: "naQXI7l6op0" },
  { title: "Banda Ban Ja", artist: "Garry Sandhu, Beat Minister", album: "Banda Ban Ja", yt: "Kp76nzS7pwA" },
  { title: "Sip Sip", artist: "Jasmine Sandlas, Intense", album: "Sip Sip", yt: "HasiFemale1" },
  { title: "Laddu", artist: "Garry Sandhu, Jasmine Sandlas", album: "Laddu", yt: "YehKaisiJag" },
  { title: "Hauli Hauli", artist: "Garry Sandhu, Tanishk Bagchi, Neha Kakkar", album: "De De Pyaar De", yt: "KaunHoyega1" },
  { title: "Do You Know Workout Mix", artist: "Diljit Dosanjh, B Praak", album: "Do You Know", yt: "MannBharrya" },
  { title: "5 Taara", artist: "Diljit Dosanjh, Jatinder Shah", album: "5 Taara", yt: "KaashAisaHo" },
  { title: "Laembadgini", artist: "Diljit Dosanjh, Jatinder Shah", album: "Laembadgini", yt: "Judaiyaan01" },
  { title: "Raat Di Gedi", artist: "Diljit Dosanjh, Jatinder Shah", album: "Raat Di Gedi", yt: "HawaBanke02" },
  { title: "Putt Jatt Da", artist: "Diljit Dosanjh, Archie, Kaater", album: "Putt Jatt Da", yt: "KabhiiTumhh" },
  { title: "Jind Mahi", artist: "Diljit Dosanjh, Manni Sandhu", album: "Jind Mahi", yt: "IshqChhupay" },
  { title: "Muchh", artist: "Diljit Dosanjh, The Boss", album: "Muchh", yt: "KuchIsTarah" },
  { title: "Welcome To My Hood", artist: "Diljit Dosanjh, Flamme", album: "G.O.A.T.", yt: "MahiVeFaakh" },
  { title: "Peaches", artist: "Diljit Dosanjh, Intense", album: "Drive Thru", yt: "BikhraHoonM" },
  { title: "Red Chilli", artist: "Diljit Dosanjh, Sia, Intense", album: "Drive Thru", yt: "LamheyJal01" },
  { title: "Caviar", artist: "Diljit Dosanjh, Intense", album: "Drive Thru", yt: "PanchiJal01" },
  { title: "Chauffeur", artist: "Diljit Dosanjh, Tory Lanez, Ikky", album: "Chauffeur", yt: "TeriYaadJal" },
  { title: "Lemonade Workout Edit", artist: "Diljit Dosanjh, Intense", album: "Drive Thru", yt: "RangonMein1" },
  { title: "Banger Gym Drop", artist: "Diljit Dosanjh, Jatinder Shah", album: "Banger", yt: "DilHarayJal" }
];
