// Category 3: Awarapan (Emraan Hashmi Heartbreak, Soulful, Passion & Melancholy Universe)
module.exports = [
  { title: "Toh Phir Aao", artist: "Mustafa Zahid, Pritam", album: "Awarapan", yt: "n_VrRuNkbrE" },
  { title: "Tera Mera Rishta Purana", artist: "Mustafa Zahid, Pritam", album: "Awarapan", yt: "P2kS3h46cIA" },
  { title: "Mahiya", artist: "Annie Khalid, Suzanne D'Mello, Pritam", album: "Awarapan", yt: "FJzE1p3mvw8" },
  { title: "Tera Mera Rishta (New Version)", artist: "Mustafa Zahid, Mithoon", album: "Awarapan", yt: "6rvUyBiBtik" },
  { title: "Toh Phir Aao (Lounge Version)", artist: "Mustafa Zahid, Pritam", album: "Awarapan", yt: "XwDV5xldudU" },
  { title: "Awarapan Jukebox", artist: "Mustafa Zahid, Annie Khalid, Pritam", album: "Awarapan", yt: "oHmXALAdydI" },
  { title: "Toh Phir Aao (Acoustic)", artist: "Mustafa Zahid, Pritam", album: "Awarapan", yt: "itoIHcocrZI" },
  { title: "Zara Sa", artist: "KK, Pritam", album: "Jannat", yt: "ZsAOnmByy38" },
  { title: "Judai", artist: "Kamran Ahmed, Pritam", album: "Jannat", yt: "7L_Qv9_zXw0" },
  { title: "Haan Tu Hain", artist: "KK, Pritam", album: "Jannat", yt: "w-v_0Z9k1_E" },
  { title: "Lambi Judai", artist: "Richa Sharma, Pritam", album: "Jannat", yt: "v91pX_8v9yE" },
  { title: "Door Na Ja", artist: "Rana Mazumder, Pritam", album: "Jannat", yt: "q9x1v_k87eA" },
  { title: "Jannat Title Theme", artist: "Pritam", album: "Jannat", yt: "AhO7mWclXOc" },
  { title: "Tu Hi Meri Shab Hai", artist: "KK, Pritam", album: "Gangster", yt: "cGNcjqXe87U" },
  { title: "Bheegi Bheegi", artist: "James, Pritam", album: "Gangster", yt: "_RZwGzElnIs" },
  { title: "Ya Ali", artist: "Zubeen Garg, Pritam", album: "Gangster", yt: "Bpj3JYLCCuA" },
  { title: "Lamha Lamha", artist: "Abhijeet Bhattacharya, Sunidhi Chauhan, Pritam", album: "Gangster", yt: "oA8b3LdE1xI" },
  { title: "Mujhe Mat Roko", artist: "Kavita Seth, Pritam", album: "Gangster", yt: "d4OGrMv_hN0" },
  { title: "Beete Lamhe", artist: "KK, Mithoon", album: "The Train", yt: "UlacMvx_VYk" },
  { title: "Teri Yaadon Mein", artist: "KK, Shreya Ghoshal, Mithoon", album: "The Train", yt: "fVeJ6sJERR4" },
  { title: "Woh Ajnabee", artist: "Mithoon, Sayeed Quadri", album: "The Train", yt: "9mN4P1v_i1s" },
  { title: "Mausam", artist: "Mithoon", album: "The Train", yt: "uN7Wp_q0L3w" },
  { title: "Zindagi Ne Zindagi Bhar Gham Diye", artist: "K.K., Mithoon", album: "The Train", yt: "7CdpHATpXXU" },
  { title: "Woh Lamhe Woh Baatein", artist: "Atif Aslam, Mithoon", album: "Zeher", yt: "1DBhic8SSKs" },
  { title: "Agar Tum Mil Jao", artist: "Shreya Ghoshal, Roop Kumar Rathod", album: "Zeher", yt: "qnQCd_nZn_g" },
  { title: "Jaane Jaa Jaane Jaa", artist: "Udit Narayan, Shreya Ghoshal", album: "Zeher", yt: "bjfKyIAlsZs" },
  { title: "Aye Bekhabar", artist: "KK, Roop Kumar Rathod", album: "Zeher", yt: "pCYojfACnzQ" },
  { title: "Aashiq Banaya Aapne Title Track", artist: "Himesh Reshammiya, Shreya Ghoshal", album: "Aashiq Banaya Aapne", yt: "0bAVd9jJE2Q" },
  { title: "Aap Ki Kashish", artist: "Himesh Reshammiya, Krishna, Ahir", album: "Aashiq Banaya Aapne", yt: "sv26LXD4GbI" },
  { title: "Mar Jaawan Mit Jaawan", artist: "Abhijeet Sawant, Sunidhi Chauhan, Himesh Reshammiya", album: "Aashiq Banaya Aapne", yt: "yktlUKTWlJg" },
  { title: "Dillagi Mein Jo Beet Jaaye", artist: "Shaan, Himesh Reshammiya", album: "Aashiq Banaya Aapne", yt: "QXJyMpxd210" },
  { title: "Bheegey Hont", artist: "Kunal Ganjawala, Anu Malik", album: "Murder", yt: "taRBVfDRukY" },
  { title: "Kaho Na Kaho", artist: "Amir Jamal, Anu Malik", album: "Murder", yt: "FBTgulBOUy0" },
  { title: "Zindagi Iss Tarah", artist: "Sonu Nigam, Anuradha Paudwal, Anu Malik", album: "Murder", yt: "BddP6PYo2gs" },
  { title: "Janaabe Ali", artist: "Shaan, Kunal Ganjawala, Krishna, Anu Malik", album: "Murder", yt: "KUpwupYj_tY" },
  { title: "Hale Dil", artist: "Harshit Saxena, Mithoon", album: "Murder 2", yt: "RLzC55ai0eo" },
  { title: "Aye Khuda", artist: "Kshitij Tarey, Saim Bhat, Mithoon", album: "Murder 2", yt: "Grr0FlC8SQA" },
  { title: "Phir Mohabbat", artist: "Mohd Irfan, Arijit Singh, Saim Bhat, Mithoon", album: "Murder 2", yt: "8v-0h5xY6gE" },
  { title: "Aa Zara", artist: "Sunidhi Chauhan, Sangeet Haldipur", album: "Murder 2", yt: "p8L3n9X0vY0" },
  { title: "Tujhko Bhulaana", artist: "Sangeet Haldipur, Siddharth Haldipur", album: "Murder 2", yt: "y9kQ5L_X8rE" },
  { title: "Teri Jhuki Nazar", artist: "Shafqat Amanat Ali, Pritam", album: "Murder 3", yt: "k6vN0qP91C0" },
  { title: "Hum Jee Lenge", artist: "Mustafa Zahid, Roxen, Pritam", album: "Murder 3", yt: "Ov0YGGSY6gY" },
  { title: "Mat Aazma Re", artist: "KK, Pritam", album: "Murder 3", yt: "OOWvmeTTp7Y" },
  { title: "Jaata Hai Tujh Tak", artist: "Nikhil D'Souza, Pritam", album: "Murder 3", yt: "cYOB941gyXI" },
  { title: "Dil Ibaadat", artist: "KK, Pritam", album: "Tum Mile", yt: "cs1e0fRyI18" },
  { title: "Tu Hi Haqeeqat", artist: "Javed Ali, Irshan Ashraf, Shadab, Pritam", album: "Tum Mile", yt: "CWHSNIpl7dg" },
  { title: "Tum Mile Title Track", artist: "Neeraj Shridhar, Pritam", album: "Tum Mile", yt: "2Vv-BfVoq4g" },
  { title: "O Meri Jaan Tum Mile", artist: "KK, Pritam", album: "Tum Mile", yt: "Pa1UPI5STLk" },
  { title: "Iss Jahaan Mein", artist: "Mohit Chauhan, Pritam", album: "Tum Mile", yt: "7shxWODIwqs" },
  { title: "Soul of Tum Mile", artist: "Pritam", album: "Tum Mile", yt: "zVUKtXI7xTM" },
  { title: "Mere Bina", artist: "Nikhil D'Souza, Pritam", album: "Crook", yt: "g6C-GUy6a3s" },
  { title: "Kya Mujhe Pyar Hai", artist: "KK, Pritam", album: "Woh Lamhe", yt: "ElZfdU54Cp8" },
  { title: "Tu Jo Nahin", artist: "Glenn John, Pritam", album: "Woh Lamhe", yt: "KUpwupYj_tY" },
  { title: "So Jaoon Main", artist: "Shreya Ghoshal, Kunal Ganjawala, Roop Kumar Rathod", album: "Woh Lamhe", yt: "iAOA8TLgqG8" },
  { title: "Chal Chale Apne Ghar", artist: "James, Pritam", album: "Woh Lamhe", yt: "w3eYf7noC8A" },
  { title: "Soniyo", artist: "Sonu Nigam, Shreya Ghoshal, Neeraj Shridhar, Raju Singh", album: "Raaz The Mystery Continues", yt: "3oMQuyaPGa4" },
  { title: "Maahi", artist: "Toshi Sabri, Sharib Sabri", album: "Raaz The Mystery Continues", yt: "YxWlaYCA8MU" },
  { title: "O Jaana Raaz", artist: "KK, Raju Singh", album: "Raaz The Mystery Continues", yt: "Zlqf9cuaOBw" },
  { title: "Kaisa Ye Raaz Hai", artist: "KK, Raju Singh", album: "Raaz The Mystery Continues", yt: "xWi8nDUjHGA" },
  { title: "Banda Ye Bindaas Hai", artist: "KK, Raju Singh", album: "Aksar", yt: "5GCfYLguTIs" },
  { title: "Jhalak Dikhla Ja", artist: "Himesh Reshammiya", album: "Aksar", yt: "2sAzb3kraoQ" },
  { title: "Lagi Lagi", artist: "Himesh Reshammiya, Sunidhi Chauhan", album: "Aksar", yt: "CeFQO9MQNqs" },
  { title: "Soniye", artist: "KK, Sunidhi Chauhan, Himesh Reshammiya", album: "Aksar", yt: "uChhQpHMmXE" },
  { title: "Pee Loon", artist: "Mohit Chauhan, Pritam", album: "Once Upon A Time In Mumbaai", yt: "k85UB5b6pJU" },
  { title: "Tum Jo Aaye", artist: "Rahat Fateh Ali Khan, Tulsi Kumar, Pritam", album: "Once Upon A Time In Mumbaai", yt: "fRJ03btNsao" },
  { title: "I Am In Love", artist: "KK, Dominique Cerejo, Pritam", album: "Once Upon A Time In Mumbaai", yt: "RuDsBrSczis" },
  { title: "Parda", artist: "Sunidhi Chauhan, Rana Mazumder, Pritam", album: "Once Upon A Time In Mumbaai", yt: "4-iO6c-JmN8" },
  { title: "Tera Deedar Hua", artist: "Rahat Fateh Ali Khan, Pritam", album: "Jannat 2", yt: "g6fnFALEseI" },
  { title: "Tujhe Sochta Hoon", artist: "KK, Pritam", album: "Jannat 2", yt: "W1S9AbHpWFY" },
  { title: "Jannat Jahan", artist: "Nikhil D'Souza, Pritam", album: "Jannat 2", yt: "1qeujW9f4So" },
  { title: "Rab Ka Shukrana", artist: "Mohit Chauhan, Pritam", album: "Jannat 2", yt: "k6GjS_Hzg8I" },
  { title: "Sang Hoon Tere", artist: "Nikhil D'Souza, Pritam", album: "Jannat 2", yt: "PLIsDVqACZ0" },
  { title: "Raaz Aankhein Teri", artist: "Arijit Singh, Jeet Gannguli", album: "Raaz Reboot", yt: "P7yRYiBiV3g" },
  { title: "Lo Maan Liya", artist: "Arijit Singh, Jeet Gannguli", album: "Raaz Reboot", yt: "Gqnnrop26Sw" },
  { title: "Dekh Lena", artist: "Arijit Singh, Tulsi Kumar, Ankit Tiwari", album: "Tum Bin 2", yt: "aDOs442shYU" },
  { title: "Hasi", artist: "Ami Mishra", album: "Hamari Adhuri Kahani", yt: "WCDXUgvddR4" },
  { title: "Hamari Adhuri Kahani Title Track", artist: "Arijit Singh, Jeet Gannguli", album: "Hamari Adhuri Kahani", yt: "S2BOXJG71FY" },
  { title: "Yeh Kaisi Jagah", artist: "Deepali Sathe, Zubeen Garg, Jeet Gannguli", album: "Hamari Adhuri Kahani", yt: "8K9eaAKLrE0" },
  { title: "Zaroori Tha", artist: "Rahat Fateh Ali Khan, Hamari Adhuri Kahani", album: "Back 2 Love", yt: "jh6Anzu3ntQ" },
  { title: "Saaware", artist: "Arijit Singh, Pritam", album: "Phantom", yt: "4O0_erwpB9E" },
  { title: "Afreen Afreen", artist: "Rahat Fateh Ali Khan, Momina Mustehsan", album: "Coke Studio Season 9", yt: "naQXI7l6op0" },
  { title: "Tera Ghata", artist: "Gajendra Verma", album: "Tera Ghata", yt: "Kp76nzS7pwA" },
  { title: "Tune Jo Na Kaha", artist: "Mohit Chauhan, Pritam", album: "New York", yt: "xWi8nDUjHGA" },
  { title: "Abhi Kuch Dino Se", artist: "Mohit Chauhan, Pritam", album: "Dil Toh Baccha Hai Ji", yt: "5GCfYLguTIs" },
  { title: "Tere Bin", artist: "Atif Aslam, Mithoon", album: "Bas Ek Pal", yt: "2sAzb3kraoQ" },
  { title: "Javeda Zindagi", artist: "Kshitij Tarey, Mithoon", album: "Anwar", yt: "CeFQO9MQNqs" },
  { title: "Maula Mere Maula", artist: "Roop Kumar Rathod, Mithoon", album: "Anwar", yt: "uChhQpHMmXE" },
  { title: "Tose Naina", artist: "Arijit Singh, Hanif Shaikh", album: "Mickey Virus", yt: "k85UB5b6pJU" },
  { title: "Suno Na Sangemarmar", artist: "Arijit Singh, Jeet Gannguli", album: "Youngistaan", yt: "fRJ03btNsao" },
  { title: "Mast Magan", artist: "Arijit Singh, Chinmayi Sripada, Shankar-Ehsaan-Loy", album: "2 States", yt: "RuDsBrSczis" },
  { title: "Chaandaniya", artist: "Mohan Kanan, Yashita Sharma, Shankar-Ehsaan-Loy", album: "2 States", yt: "4-iO6c-JmN8" },
  { title: "Offo", artist: "Aditi Singh Sharma, Benny Dayal, Shankar-Ehsaan-Loy", album: "2 States", yt: "g6fnFALEseI" }
];
