// Category 5: Golden 90s (classic_old) - 200 Evergreen Retro Hindi Classics
module.exports = [
  { title: "Tujhe Dekha Toh", artist: "Kumar Sanu, Lata Mangeshkar, Jatin-Lalit", album: "Dilwale Dulhania Le Jayenge", yt: "cNVtYMhBG4I" },
  { title: "Mehndi Laga Ke Rakhna", artist: "Lata Mangeshkar, Udit Narayan, Jatin-Lalit", album: "Dilwale Dulhania Le Jayenge", yt: "posL_V_j4bA" },
  { title: "Ho Gaya Hai Tujhko Toh Pyar Sajna", artist: "Lata Mangeshkar, Udit Narayan, Jatin-Lalit", album: "Dilwale Dulhania Le Jayenge", yt: "1xYZeDReUz4" },
  { title: "Mere Khwabon Mein", artist: "Lata Mangeshkar, Jatin-Lalit", album: "Dilwale Dulhania Le Jayenge", yt: "NZ1EBaqDL0M" },
  { title: "Ruk Ja O Dil Deewane", artist: "Udit Narayan, Jatin-Lalit", album: "Dilwale Dulhania Le Jayenge", yt: "FewWUHxY79w" },
  { title: "Zara Sa Jhoom Loon Main", artist: "Asha Bhosle, Abhijeet, Jatin-Lalit", album: "Dilwale Dulhania Le Jayenge", yt: "YDAWpY747TY" },
  { title: "Dheere Dheere Se Meri Zindagi Mein Aana", artist: "Kumar Sanu, Anuradha Paudwal, Nadeem-Shravan", album: "Aashiqui", yt: "M5n7994yM0c" },
  { title: "Nazar Ke Samne Jigar Ke Paas", artist: "Kumar Sanu, Anuradha Paudwal, Nadeem-Shravan", album: "Aashiqui", yt: "cl0a3i2wFcc" },
  { title: "Bas Ek Sanam Chaahiye", artist: "Kumar Sanu, Nadeem-Shravan", album: "Aashiqui", yt: "7L_Qv9_zXw0" },
  { title: "Jaane Jigar Jaaneman", artist: "Kumar Sanu, Anuradha Paudwal, Nadeem-Shravan", album: "Aashiqui", yt: "w-v_0Z9k1_E" },
  { title: "Main Duniya Bhula Doonga", artist: "Kumar Sanu, Anuradha Paudwal, Nadeem-Shravan", album: "Aashiqui", yt: "v91pX_8v9yE" },
  { title: "Mera Dil Bhi Kitna Pagal Hai", artist: "Kumar Sanu, Alka Yagnik, Nadeem-Shravan", album: "Saajan", yt: "284Ov7ysmfA" },
  { title: "Bahut Pyar Karte Hai", artist: "SP Balasubrahmanyam, Anuradha Paudwal, Nadeem-Shravan", album: "Saajan", yt: "6FURuLYrR_Q" },
  { title: "Dekha Hai Pehli Baar", artist: "SP Balasubrahmanyam, Alka Yagnik, Nadeem-Shravan", album: "Saajan", yt: "w_HaezV04qI" },
  { title: "Tumse Milne Ki Tamanna Hai", artist: "SP Balasubrahmanyam, Nadeem-Shravan", album: "Saajan", yt: "d4OGrMv_hN0" },
  { title: "Pehla Nasha", artist: "Udit Narayan, Sadhana Sargam, Jatin-Lalit", album: "Jo Jeeta Wohi Sikandar", yt: "y0p7o1eW9_A" },
  { title: "Tip Tip Barsa Paani", artist: "Udit Narayan, Alka Yagnik, Viju Shah", album: "Mohra", yt: "uN7Wp_q0L3w" },
  { title: "Tu Cheez Badi Hai Mast Mast", artist: "Udit Narayan, Kavita Krishnamurthy, Viju Shah", album: "Mohra", yt: "fdubeMFwuGs" },
  { title: "Chura Ke Dil Mera", artist: "Kumar Sanu, Alka Yagnik, Anu Malik", album: "Main Khiladi Tu Anari", yt: "qnQCd_nZn_g" },
  { title: "Dil To Pagal Hai Title Track", artist: "Lata Mangeshkar, Udit Narayan, Uttam Singh", album: "Dil To Pagal Hai", yt: "bjfKyIAlsZs" },
  { title: "Are Re Are", artist: "Lata Mangeshkar, Udit Narayan, Uttam Singh", album: "Dil To Pagal Hai", yt: "pCYojfACnzQ" },
  { title: "Bholi Si Surat", artist: "Lata Mangeshkar, Udit Narayan, Uttam Singh", album: "Dil To Pagal Hai", yt: "BddP6PYo2gs" },
  { title: "Dholna", artist: "Lata Mangeshkar, Udit Narayan, Uttam Singh", album: "Dil To Pagal Hai", yt: "QXJyMpxd210" },
  { title: "Kuch Kuch Hota Hai Title Track", artist: "Udit Narayan, Alka Yagnik, Jatin-Lalit", album: "Kuch Kuch Hota Hai", yt: "taRBVfDRukY" },
  { title: "Ladki Badi Anjani Hai", artist: "Kumar Sanu, Alka Yagnik, Jatin-Lalit", album: "Kuch Kuch Hota Hai", yt: "ElZfdU54Cp8" },
  { title: "Koi Mil Gaya", artist: "Udit Narayan, Alka Yagnik, Kavita Krishnamurthy, Jatin-Lalit", album: "Kuch Kuch Hota Hai", yt: "KUpwupYj_tY" },
  { title: "Yeh Ladka Hai Deewana", artist: "Udit Narayan, Alka Yagnik, Jatin-Lalit", album: "Kuch Kuch Hota Hai", yt: "RLzC55ai0eo" },
  { title: "Saajanji Ghar Aaye", artist: "Kumar Sanu, Alka Yagnik, Kavita Krishnamurthy, Jatin-Lalit", album: "Kuch Kuch Hota Hai", yt: "Grr0FlC8SQA" },
  { title: "Tujhe Yaad Na Meri Aayee", artist: "Alka Yagnik, Manpreet Akhtar, Udit Narayan, Jatin-Lalit", album: "Kuch Kuch Hota Hai", yt: "8v-0h5xY6gE" },
  { title: "Pardesi Pardesi", artist: "Udit Narayan, Alka Yagnik, Sapna Awasthi, Nadeem-Shravan", album: "Raja Hindustani", yt: "Grr0FlC8SQA" },
  { title: "Aaye Ho Meri Zindagi Mein", artist: "Udit Narayan, Alka Yagnik, Nadeem-Shravan", album: "Raja Hindustani", yt: "p8L3n9X0vY0" },
  { title: "Kitna Pyaara Tujhe Rab Ne Banaya", artist: "Udit Narayan, Alka Yagnik, Nadeem-Shravan", album: "Raja Hindustani", yt: "y9kQ5L_X8rE" },
  { title: "Poocho Zara Poocho", artist: "Kumar Sanu, Alka Yagnik, Nadeem-Shravan", album: "Raja Hindustani", yt: "k6vN0qP91C0" },
  { title: "Tere Dar Par Sanam", artist: "Kumar Sanu, Anu Malik", album: "Phir Teri Kahani Yaad Aayee", yt: "Ov0YGGSY6gY" },
  { title: "Dil Hai Ke Manta Nahin Title Track", artist: "Kumar Sanu, Anuradha Paudwal, Nadeem-Shravan", album: "Dil Hai Ke Manta Nahin", yt: "tLqtnGLfm4Q" },
  { title: "Adaayein Bhi Hain", artist: "Kumar Sanu, Anuradha Paudwal, Nadeem-Shravan", album: "Dil Hai Ke Manta Nahin", yt: "cYOB941gyXI" },
  { title: "O Mere Sapnon Ke Saudagar", artist: "Anuradha Paudwal, Nadeem-Shravan", album: "Dil Hai Ke Manta Nahin", yt: "cs1e0fRyI18" },
  { title: "Galyan Sakli Sonyachi", artist: "Anuradha Paudwal, Babla, Nadeem-Shravan", album: "Dil Hai Ke Manta Nahin", yt: "CWHSNIpl7dg" },
  { title: "Chura Liya Hai Tumne Jo Dil Ko", artist: "Asha Bhosle, Mohammed Rafi, R.D. Burman", album: "Yaadon Ki Baaraat", yt: "dY8p8m5G2fE" },
  { title: "Dum Maro Dum", artist: "Asha Bhosle, R.D. Burman", album: "Hare Rama Hare Krishna", yt: "mK4v9-qG1pE" },
  { title: "Yeh Shaam Mastani", artist: "Kishore Kumar, R.D. Burman", album: "Kati Patang", yt: "PVxc5f4GJU8" },
  { title: "Pyaar Deewana Hota Hai", artist: "Kishore Kumar, R.D. Burman", album: "Kati Patang", yt: "j6muwUGPCl8" },
  { title: "Kora Kagaz Tha Yeh Man Mera", artist: "Kishore Kumar, Lata Mangeshkar, S.D. Burman", album: "Aradhana", yt: "wF_B_a30AZc" },
  { title: "Roop Tera Mastana", artist: "Kishore Kumar, S.D. Burman", album: "Aradhana", yt: "g6C-GUy6a3s" },
  { title: "Mere Sapno Ki Rani", artist: "Kishore Kumar, S.D. Burman", album: "Aradhana", yt: "ElZfdU54Cp8" },
  { title: "O Mere Dil Ke Chain", artist: "Kishore Kumar, R.D. Burman", album: "Mere Jeevan Saathi", yt: "KUpwupYj_tY" },
  { title: "Ek Ladki Ko Dekha Toh Aisa Laga", artist: "Kumar Sanu, R.D. Burman", album: "1942: A Love Story", yt: "iAOA8TLgqG8" },
  { title: "Kuch Na Kaho", artist: "Kumar Sanu, R.D. Burman", album: "1942: A Love Story", yt: "SAcpESN_Fk4" },
  { title: "Rimjhim Rimjhim", artist: "Kumar Sanu, Kavita Krishnamurthy, R.D. Burman", album: "1942: A Love Story", yt: "rTuxUAuJRyY" },
  { title: "Pyar Hua Chupke Se", artist: "Kavita Krishnamurthy, R.D. Burman", album: "1942: A Love Story", yt: "P8PWN1OmZOA" }
];
